- projects/portal/src/app/pages/mint/cdps/cdps.component.ts
- projects/portal/src/app/utils/function.ts
- projects/portal/src/app/views/mint/cdps/cdps.component.html
- projects/portal/src/app/views/mint/cdps/cdps.component.ts
This PR is for PR [#241](https://github.com/UnUniFi/utils/pull/241).
> fix: ununifi/mint/cdps

- projects/portal/src/app/models/keys/key-backup-dialog.service.ts
- projects/portal/src/app/views/keys/key-backup-dialog/key-backup-dialog.component.ts
@Senna46 
Please review.
fix. [https://github.com/UnUniFi/web-apps/issues/27](https://github.com/UnUniFi/web-apps/issues/27)
the case was different. ( privatekey vs privateKey )
> feat: fix donwload txt file

- projects/landing-page/src/app/models/apply.application.service.ts
- projects/portal/src/app/models/auctions/auction.application.service.ts
- projects/portal/src/app/models/cdps/cdp.application.service.ts
- projects/portal/src/app/models/cosmos/staking.application.service.ts
- projects/portal/src/app/models/keys/key.application.service.ts
[https://github.com/UnUniFi/web-apps/issues/16](https://github.com/UnUniFi/web-apps/issues/16)
・snackbar with error message should close manually
> feat: snackbar with error message should close manually

- projects/explorer/src/app/app.component.html
- projects/explorer/src/app/app.component.ts
- projects/explorer/src/app/views/app.component.html
- projects/explorer/src/app/views/app.component.ts
- projects/portal/src/app/app.component.html
- projects/portal/src/app/app.component.ts
- projects/portal/src/app/views/app.component.html
- projects/portal/src/app/views/app.component.ts
> configType=>config

- projects/portal/src/app/models/cosmos/staking.service.ts
@mkXultra 
plz review 🙏 
I checked this fix locally and confirm tx success.
- Fix commission rate unit conversion
unexpected result validator: http://a.private-test.ununifi.cauchye.net:1317/cosmos/staking/v1beta1/validators/ununifivaloper10qfku63l7exn2v59gnvnlgqtwq45p0403rtyz7
expected result validator: http://a.private-test.ununifi.cauchye.net:1317/cosmos/staking/v1beta1/validators/ununifivaloper1pusc99rh7tzstjklttuw98pnsj968d8tr6glcg
unexpected result json
```json
{
"validator": {
"operator_address": "ununifivaloper10qfku63l7exn2v59gnvnlgqtwq45p0403rtyz7",
"consensus_pubkey": {
"@type": "/cosmos.crypto.ed25519.PubKey",
"key": "ErcfXYAlJwa1BOVpdsMuftmCjokOzlkwM07fW0Fka5I="
},
"jailed": false,
"status": "BOND_STATUS_BONDED",
"tokens": "190000000",
"delegator_shares": …
```
> fix: create validator commission rate unit

- projects/portal/src/app/models/wallets/wallet.application.service.ts
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-backup-mnemonic-and-private-key-wizard-dialog/ununifi-backup-mnemonic-and-private-key-wizard-dialog.component.ts
> fix: password saving feature and change backup file's extension from json to text

- projects/explorer/src/app/models/cosmos-sdk.service.ts
- Apply portal fix to Explorer
[https://github.com/UnUniFi/web-apps/pull/32/commits/62f43c62b2d8cf74b9a727d4540b32678ea2ddd2](https://github.com/UnUniFi/web-apps/pull/32/commits/62f43c62b2d8cf74b9a727d4540b32678ea2ddd2)
- I check 
can go to validator page from validators list page
> feat: fix config service bech32prefix

- projects/portal/src/app/pages/accounts/accounts-routing.module.ts
- projects/portal/src/app/pages/accounts/create/create-routing.module.ts
- projects/portal/src/app/pages/accounts/create/create.module.ts
- projects/portal/src/app/pages/accounts/create/simple/simple-routing.module.ts
- projects/portal/src/app/pages/accounts/create/simple/simple.component.html
- projects/portal/src/app/pages/accounts/create/simple/simple.component.ts
- projects/portal/src/app/pages/accounts/create/simple/simple.module.ts
- projects/portal/src/app/views/accounts/create/simple/simple.component.html
- projects/portal/src/app/views/accounts/create/simple/simple.component.ts
- projects/portal/src/app/views/accounts/create/simple/simple.module.ts
@mkXultra 
plz review 🙏 
Screenshot
> feat: accounts create simple

- projects/explorer/editions/ununifi/launch/ununifi-9-beta-test-v1/firebase-hosting/config.js
- projects/explorer/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi-9-beta-test-v1/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
> fix: disable faucet on beta test

- .github/workflows/cd-firebase-ununifi-8-private-test.yml
- .github/workflows/cd-firebase-ununifi-alpha-test.yml
- .github/workflows/cd-firebase-ununifi.yml
> hotfix: disable cd on release published

- projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.html
- projects/portal/src/app/views/staking/create-validator/create-validator.component.html
> hotfix: minimum gas price readonly

- projects/portal/editions/ununifi/launch/ununifi-9-beta-test-v1/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
> hotfix: disable monitor on beta test

- projects/portal/src/app/app.component.ts
@Senna46 
Please review.
Fixed to jump from the search bar to the block page. 
[https://github.com/UnUniFi/web-apps/issues/33](https://github.com/UnUniFi/web-apps/issues/33)
> fix: search bar link of block (add /explorer)

- projects/explorer/src/app/views/proposals/proposal/proposal.component.html
- projects/explorer/src/app/views/proposals/proposal/proposal.component.ts
- projects/explorer/src/app/views/proposals/proposals.component.html
- projects/portal/src/app/views/vote/proposals/proposal/proposal.component.html
- projects/portal/src/app/views/vote/proposals/proposal/proposal.component.ts
- projects/portal/src/app/views/vote/proposals/proposals.component.html
Minor Changes for /proposals & /proposals/proposals
@YasunoriMATSUOKA plz review some time.
> chore: proposal param

- projects/portal/src/app/pages/delegate/validators/validators.component.html
- projects/portal/src/app/pages/delegate/validators/validators.component.ts
- projects/portal/src/app/views/delegate/validators/validators.component.html
- projects/portal/src/app/views/delegate/validators/validators.component.ts
- Implement a list of possible required delegations under the validator list.
https://github.com/UnUniFi/beta-test/issues/3
@mkXultra @YasunoriMATSUOKA 
plz review
> feat: add users delegations info to delegate page

- projects/portal/src/app/app.module.ts
- projects/portal/src/app/pages/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.html
- projects/portal/src/app/pages/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.ts
- projects/portal/src/app/pages/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.html
- projects/portal/src/app/pages/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.ts
- projects/portal/src/app/pages/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/delegate/invalid-validator-confirm-dialog/inactive-validator-confirm-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/invalid-validator-confirm-dialog/inactive-validator-confirm-dialog.component.ts
- projects/portal/src/app/views/dialogs/delegate/invalid-validator-confirm-dialog/inactive-validator-confirm-dialog.module.ts
- projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.ts
This PR is same as https://github.com/UnUniFi/web-apps/pull/104. 
There is one different commit mixed in, but I think it is not a problem.
> fix: delegate dialog to disable redelegate same validator and warn on delegate to an inactive validator

- projects/portal/src/app/pages/accounts/create/simple/simple.component.html
- projects/portal/src/app/pages/accounts/create/simple/simple.component.ts
- projects/portal/src/app/views/accounts/create/simple/simple.component.html
- projects/portal/src/app/views/accounts/create/simple/simple.component.ts
- projects/portal/src/app/views/accounts/create/simple/simple.module.ts
@mkXultra 
plz review 🙏 
Screenshot
> feat: add buttons to account create simple page

- projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/delegate-menu-dialog/delegate-menu-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/vote/deposit/deposit-form-dialog.component.html
- projects/portal/src/app/views/dialogs/vote/vote/vote-form-dialog.component.html
> fix: dialog scroll

- projects/explorer/src/app/views/dashboard/validators/validators.component.html
- projects/explorer/src/app/views/validators/validators.component.html
- projects/portal/src/app/pages/delegate/validators/validators.component.html
- projects/portal/src/app/pages/delegate/validators/validators.component.ts
- projects/portal/src/app/pages/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.html
- projects/portal/src/app/pages/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.ts
- projects/portal/src/app/views/delegate/validators/validators.component.html
- projects/portal/src/app/views/delegate/validators/validators.component.ts
- projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/delegate-menu-dialog/delegate-menu-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.html
@YasunoriMATSUOKA Please review it sometime.
Changed to show Moniker on the following pages. (Functions have been tested.)
- Explorer
- Top page Validators list
- Validators Page
- Portal
- Delegate Validators Page
- Delegate menu dialog
- Delegate form dialog
- Redelegate form dialog
- Undelegate form dialog
> feat: validators show moniker

- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-create-wallet-form-dialog/ununifi-create-wallet-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-mnemonic-form-dialog/ununifi-import-wallet-with-mnemonic-form-dialog.component.ts
@mkXultra 
plz review 🙏 
Screenshot (create)
Screenshot (import)
> fix: prevent overwrite with same wallet id

- projects/landing-page/src/app/views/home/home.component.html
Please review, if this button needed.
> feat: add explorer link button to landing page

- projects/portal/src/app/app.module.ts
- projects/portal/src/app/models/wallets/wallet.application.service.ts
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-backup-private-key-wizard-dialog/ununifi-backup-private-key-wizard-dialog.component.html
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-backup-private-key-wizard-dialog/ununifi-backup-private-key-wizard-dialog.component.ts
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-backup-private-key-wizard-dialog/ununifi-backup-private-key-wizard-dialog.module.ts
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-private-key-form-dialog/ununifi-import-wallet-with-private-key-form-dialog.component.html
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-private-key-form-dialog/ununifi-import-wallet-with-private-key-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-private-key-form-dialog/ununifi-import-wallet-with-private-key-form-dialog.module.ts
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-select-create-import-dialog/ununifi-select-create-import-dialog.component.ts
> feat: import wallet with private key

- projects/portal/src/app/views/staking/create-validator-simple/create-validator-simple.component.html
@mkXultra 
plz review 🙏 
- Fix create validator tx page's title from "Upload file here to be Validator!" to "Upload wallet-backup file here to be Validator". (This is a fix of a request from Neukind.)
> fix: portal create validator simple title

- projects/portal/src/app/views/balance/balance.component.html
@mkXultra 
plz review 🙏 
- Fix wrong explorer validator details page link.
- OK: https://beta-test.ununifi.io/explorer/validators/ununifivaloper1afmk9lky6a6wey4wwtdwaj49xjdks0nf0uyj2h
- NG: https://beta-test.ununifi.io/explorer/cosmos/staking/validators/ununifivaloper1afmk9lky6a6wey4wwtdwaj49xjdks0nf0uyj2h
> fix: portal home validator link

- projects/explorer/src/app/views/dashboard/dashboard.component.html
@mkXultra 
plz review 🙏 
Before
After
> fix: explorer dashboard inflation margin bottom

- projects/explorer/src/app/views/app.component.html
- projects/explorer/src/index.html
@mkXultra 
Plz review 🙏 
Before
After
> fix: explorer title from telescope to explorer

- projects/portal/src/app/views/app.component.html
@mkXultra 
plz review 🙏 
Before
After
> fix: disable bank send navigation

- projects/explorer/src/app/app.component.ts
- projects/explorer/src/environments/environment.prod.ts
- projects/explorer/src/environments/environment.ts
- projects/explorer/src/index.html
- projects/explorer/src/main.ts
- projects/explorer/tsconfig.app.json
- projects/portal/src/app/app.component.ts
- projects/portal/src/index.html
- projects/portal/src/main.ts
- projects/portal/tsconfig.app.json
- Delete Google Analytics.
@YasunoriMATSUOKA
delete code #141 
plz review
> fix: delete analytics

- projects/landing-page/src/app/views/home/home.component.html
I confirmed that a new window will be launched in another tab when I click the link. 
Please review, if necessary.
> feat: links will be opened in another tab

- projects/landing-page/src/app/views/home/home.component.css
- projects/landing-page/src/app/views/home/home.component.html
I confirmed that hover the cursor to see the white dots.
https://user-images.githubusercontent.com/75844498/167413435-ce916764-0378-440b-9975-0c1ad2af2a58.mp4
Please review, if necessary.
> feat: the point will appear when cursor on

- projects/landing-page/src/app/views/home/home.component.html
I confirmed that the pdf file can be downloaded from add link.
Please review, if necessarry.
> feat: add onepage download link

- projects/portal/src/app/app.component.ts
@Senna46 
cc: @YasunoriMATSUOKA 
Please review.
The Portal alse has account & tx components, 
but I thought it would be better to integrate it into Explorer's.
(And if possible, I want to remove some components not used. )
> fix: search bar redirect url 

- projects/portal/src/environments/environment.prod.ts
- projects/portal/src/environments/environment.ts
Found an leak in #142, will remove gtagId.
> fix: delete environment gtag

- projects/portal/src/app/models/cosmos/staking.application.service.ts
- projects/portal/src/app/models/cosmos/staking.service.ts
This PR enables you to use Keplr wallet with Redelegation / Undelegation function.
> feat: Keplr Redelegation and Undelegation

- projects/explorer/src/app/pages/proposals/proposals.component.html
- projects/explorer/src/app/pages/proposals/proposals.component.ts
- projects/explorer/src/app/views/proposals/proposals.component.html
- projects/explorer/src/app/views/proposals/proposals.component.ts
- projects/portal/src/app/pages/vote/proposals/proposal/proposal.component.ts
- projects/portal/src/app/pages/vote/proposals/proposals.component.html
- projects/portal/src/app/pages/vote/proposals/proposals.component.ts
- projects/portal/src/app/views/vote/proposals/proposals.component.html
- projects/portal/src/app/views/vote/proposals/proposals.component.ts
Fixed an issue the vote count was not displayed until the vote end.
> fix: proposal fix tally

- projects/explorer/editions/ununifi/launch/ununifi-8-private-test/firebase-hosting/config.js
- projects/explorer/editions/ununifi/launch/ununifi-9-beta-test-v1/firebase-hosting/config.js
- projects/explorer/editions/ununifi/launch/ununifi-alpha-test/firebase-hosting/config.js
- projects/explorer/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
- projects/explorer/editions/ununifi/launch/ununifi/firebase-hosting/config.js
- projects/explorer/src/app/models/config.service.ts
- projects/explorer/src/assets/config.js
- projects/portal/editions/ununifi/launch/ununifi-8-private-test/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi-9-beta-test-v1/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi-alpha-test/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi/firebase-hosting/config.js
- projects/portal/src/app/models/cosmos/gov.application.service.ts
- projects/portal/src/app/models/cosmos/gov.service.ts
- projects/portal/src/app/models/cosmos/staking.application.service.ts
- projects/portal/src/app/models/cosmos/staking.service.ts
- projects/portal/src/app/views/dialogs/vote/vote/vote-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-select-wallet-dialog/ununifi-select-wallet-dialog.component.ts
- projects/portal/src/assets/config.js
This PR enables you to use Keplr wallet with Voting / Depositing function.
- Removed keplr wallets in ununifi select dialog.
- Fixed a bug when connecting to keplr wallet.
- Fixed a bug when voting No with veto/ No/ abstain
> feat: keplr gov

- projects/portal/src/app/app-routing.module.ts
- projects/portal/src/app/models/cosmos/slashing.application.service.ts
- projects/portal/src/app/models/cosmos/slashing.service.ts
- projects/portal/src/app/models/cosmos/tx-common.service.ts
- projects/portal/src/app/pages/slashing/slashing-routing.module.ts
- projects/portal/src/app/pages/slashing/slashing.module.ts
- projects/portal/src/app/pages/slashing/unjail-simple/unjail-simple.component.html
- projects/portal/src/app/pages/slashing/unjail-simple/unjail-simple.component.ts
- projects/portal/src/app/pages/slashing/unjail/unjail.component.html
- projects/portal/src/app/pages/slashing/unjail/unjail.component.ts
- projects/portal/src/app/views/slashing/slashing.module.ts
- projects/portal/src/app/views/slashing/unjail-simple/unjail-simple.component.html
- projects/portal/src/app/views/slashing/unjail-simple/unjail-simple.component.ts
- projects/portal/src/app/views/slashing/unjail-simple/unjail-simple.module.ts
- projects/portal/src/app/views/slashing/unjail/unjail.component.html
- projects/portal/src/app/views/slashing/unjail/unjail.component.ts
- projects/portal/src/app/views/slashing/unjail/unjail.module.ts
@mkXultra 
plz review 🙏 
This feature is implemented for jailed node owners to unjail when slashing occur.
URL sample (This is not working now, because it is not deployed. but, in local, this has been already debug and confirmed.)
https://alpha-test.ununifi.io/portal/slashing/unjail/simple?delegator_address=ununifi1z6yvkm2gvdqgc9jwlrg8rphwyxtup4zy26zypx
tx
https://alpha-test.ununifi.io/explorer/txs/7B736D116586F8BF079CF5BBF66B46D36B023510462D3D35544033F53CDE0B97
validator
https://alpha-test.ununifi.io/explorer/validators/ununifivaloper1z6yvkm2gvdqgc9jwlrg8rphwyxtup4zylxhrhf
> feat: implement slashing unjail and fix to support tx fee both 0 and not 0

- projects/explorer/editions/ununifi/launch/ununifi/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi/firebase-hosting/config.js
@mkXultra 
plz review 🙏 
This is a preparation for ununifi-test-v2 launch.
> feat: ununifi-test-v2 config

- projects/portal/src/app/models/cosmos/tx-common.service.ts
- projects/portal/src/app/models/wallets/wallet.application.service.ts
The following features are disabled in the main branch.
- Create new Keplr wallet
- signing with existing Keplr wallet
> hotfix: disable keplr wallet

- projects/portal/src/app/models/cosmos/tx-common.model.ts
- projects/portal/src/app/models/cosmos/tx-common.service.ts
- projects/portal/src/app/models/keplr/keplr.service.ts
Tx send with zero fee is now possible.
need to suggestChain() again!
> hotfix: tx with 0 fee

- projects/portal/src/app/models/cosmos/tx-common.model.ts
- projects/portal/src/app/models/cosmos/tx-common.service.ts
- projects/portal/src/app/models/keplr/keplr.service.ts
This PR is as same as https://github.com/UnUniFi/web-apps/pull/173
> feat: zero fee tx

- projects/portal/src/app/models/cosmos/bank.application.service.ts
- projects/portal/src/app/models/cosmos/bank.service.ts
This PR enables you to use Keplr wallet with sending tokens.
> feat: keplr bank

- projects/portal/src/app/models/auctions/auction.application.service.ts
- projects/portal/src/app/models/auctions/auction.infrastructure.service.ts
- projects/portal/src/app/models/auctions/auction.service.ts
- projects/portal/src/app/pages/auction/auctions/auction/place-bid/place-bid.component.ts
This PR enables you to use Keplr wallet with auctions.
> feat: keplr auctions

- projects/explorer/src/app/models/cosmos/tx-common.service.ts
- projects/portal/src/app/models/cosmos/gov.service.ts
- projects/portal/src/app/models/cosmos/staking.application.service.ts
- projects/portal/src/app/models/cosmos/staking.service.ts
- projects/portal/src/app/models/cosmos/tx-common.service.ts
- projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/vote/deposit/deposit-form-dialog.component.html
- projects/portal/src/app/views/dialogs/vote/deposit/deposit-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/vote/vote/vote-form-dialog.component.html
- projects/portal/src/app/views/dialogs/vote/vote/vote-form-dialog.component.ts
@mkXultra 
plz review 🙏 
- delegate
- vote
I changed gasRatio as follows.
- low 1.1 -> 0
- average 2 -> 1.1
- high 3 -> 2
I changed default gas limit from 200000 to 1000000 because an error occur on debug redelegate feature.
I would like to consider commonization at another time, but now I have fix with a simple way.
Screenshot
> hotfix: change default to 0 fee and change default gas limit from 200000 to 1000000

- projects/landing-page/src/app/views/home/home.component.html
@YasunoriMATSUOKA  cc: @KimuraYu45z 
Please review.
I have checked jump to [https://medium.com/@ununifi](https://medium.com/@ununifi)
> fix: add BLOG button (link to medium)

- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-create-wallet-form-dialog/ununifi-create-wallet-form-dialog.component.html
This PR is same as https://github.com/UnUniFi/web-apps/pull/185
> fix: disable import feature on create dialog

- projects/explorer/editions/ununifi/launch/ununifi/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi/firebase-hosting/config.js
@mkXultra @Senna46 
plz review 🙏
> hotfix: chain id from ununifi test v2 to ununifi beta v1

- projects/portal/src/app/views/delegate/validators/validators.component.html
> feat: validators list layout

- projects/explorer/src/app/views/proposals/proposals.component.html
@YasunoriMATSUOKA , cc @KimuraYu45z 
Please. review.
- before
- after
In additional, should I set pagination to proposals?
> feat: Set the order of proposals in descending order

- projects/portal/src/app/app.module.ts
- projects/portal/src/app/models/cosmos/distribution.application.service.ts
- projects/portal/src/app/models/cosmos/distribution.service.ts
- projects/portal/src/app/pages/dialogs/delegate/delegate-menu-dialog/delegate-menu-dialog.component.html
- projects/portal/src/app/pages/dialogs/delegate/delegate-menu-dialog/delegate-menu-dialog.component.ts
- projects/portal/src/app/pages/dialogs/delegate/withdraw-validator-commission-form-dialog/withdraw-validator-commission-form-dialog.component.html
- projects/portal/src/app/pages/dialogs/delegate/withdraw-validator-commission-form-dialog/withdraw-validator-commission-form-dialog.component.ts
- projects/portal/src/app/pages/dialogs/delegate/withdraw-validator-commission-form-dialog/withdraw-validator-commission-form-dialog.module.ts
- projects/portal/src/app/views/dialogs/delegate/delegate-menu-dialog/delegate-menu-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/delegate-menu-dialog/delegate-menu-dialog.component.ts
- projects/portal/src/app/views/dialogs/delegate/withdraw-validator-commission-form-dialog/withdraw-validator-commission-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/withdraw-validator-commission-form-dialog/withdraw-validator-commission-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/delegate/withdraw-validator-commission-form-dialog/withdraw-validator-commission-form-dialog.module.ts
Please review.
- show claimable validator commission
- withdraw validator commission
> feat: claimable validator commission

- package-lock.json
- package.json
- projects/explorer/src/app/pages/accounts/account/account.component.ts
- projects/explorer/src/app/views/accounts/account/account.component.ts
- projects/explorer/src/app/views/proposals/proposal/proposal.component.ts
- projects/explorer/src/app/views/proposals/proposals.component.ts
- projects/explorer/src/app/views/txs/tx/tx.component.ts
- projects/portal/src/app/models/auctions/auction.infrastructure.service.ts
- projects/portal/src/app/models/cdps/cdp.infrastructure.service.ts
- projects/portal/src/app/models/cosmos/gentx.service.ts
- projects/portal/src/app/models/cosmos/gov.service.ts
- projects/portal/src/app/models/cosmos/staking.service.ts
- projects/portal/src/app/models/cosmos/tx-common.service.ts
- projects/portal/src/app/models/wallets/metamask/metamask.infrastructure.service.ts
- projects/portal/src/app/pages/accounts/account/account.component.ts
- projects/portal/src/app/pages/auction/auctions/auction/auction.component.ts
- projects/portal/src/app/pages/auction/auctions/auction/place-bid/place-bid.component.ts
- projects/portal/src/app/pages/auction/auctions/auctions.component.ts
- projects/portal/src/app/pages/balance/balance.component.ts
- projects/portal/src/app/views/accounts/account/account.component.ts
- projects/portal/src/app/views/cosmos/staking/validators/validator/validator.component.ts
- projects/portal/src/app/views/dialogs/vote/deposit/deposit-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/vote/vote/vote-form-dialog.component.ts
- projects/portal/src/app/views/txs/tx/tx.component.ts
- projects/portal/src/app/views/vote/proposals/proposal/proposal.component.ts
- projects/portal/src/app/views/vote/proposals/proposals.component.ts
- projects/portal/src/assets/config.js
- projects/portal/src/polyfills.ts
not working...
transaction to be signed
```
{"body":{"messages":[{"@type":"/cosmos.bank.v1beta1.MsgSend","from_address":"ununifi1amt7px7zs9u0000ptwe6tggxzv9lrnuxpqu2ke","to_address":"ununifi1pstzwm0vyqzvrv7klcy8x6f2sfquvwvx0y0ngy","amount":[{"denom":"uguu","amount":"10"}]}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[{"public_key":{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"A3AmWjffPIhtNpKvG4IQwvi9b7QAes2xxMIBLGY5if/0"},"mode_info":{"single":{"mode":"SIGN_MODE_DIRECT"}},"sequence":"0"}],"fee":{"amount":[{"denom":"uguu","amount":"1362"}],"gas_limit":"90737","payer":"","granter":""}},"chain_id":"test","account_number":"1"}
```
> feat: latest-cosmos-client-for-metamask

- projects/explorer/editions/ununifi/launch/ununifi-alpha-test/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi-alpha-test/firebase-hosting/config.js
FYI
sorry, previous PR contains mistake in config.js. (I have removed chainName unintentionally. It is necessary for Keplr.)
If CI is OK, I will merge this without review.
> fix: config.js on alpha-test to recover chainName

- projects/explorer/src/assets/config.js
- projects/portal/src/assets/config.js
@mkXultra 
plz review 🙏 
(Quick fix for alpha-test environment has been completed yesterday. But, for debug configs have not been fixed. This PR will fix them. )
> fix: config.js to recover chainName for debug

- README.md
- projects/explorer/README.md
- projects/landing-page-html/README.md
- projects/portal/README.md
> docs: readme of web apps

- projects/explorer/src/app/views/dashboard/validators/validators.component.html
Please review. 🙏 
- Inactive (after)
- Inactive (before)
> fix: validator field disappearing when InActive

- .github/workflows/cd-firebase-ununifi-beta-test.yml
> fix: beta cd to change target branch from main to release

- angular.json
plz review 🙏 
Sorry, I have removed unintentionally marketplace related angular.json settings when removing landing-page settings.
I fixed this.
> fix: recover unintentional removal of marketplace angular json

- projects/explorer/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
- projects/marketplace/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
> fix: for release to change config js chain name from beta to beta test to distinct between main beta and beta test

- projects/portal/src/app/models/cosmos/tx-common.service.ts
- projects/portal/src/app/models/wallets/wallet.application.service.ts
- projects/shared/src/lib/models/cosmos/tx/common/tx-common.service.ts
- projects/shared/src/lib/models/wallets/wallet.application.service.ts
> feat: disable metamask related feature

- projects/explorer/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
- projects/marketplace/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
> feat: config.js for new beta test(ununifi-beta-test-v2)

- .github/workflows/cd-firebase-ununifi-test.yml
- package.json
- projects/explorer/editions/ununifi/launch/ununifi-test/README.md
- projects/explorer/editions/ununifi/launch/ununifi-test/firebase-hosting/config.js
- projects/marketplace/editions/ununifi/launch/ununifi-test/README.md
- projects/marketplace/editions/ununifi/launch/ununifi-test/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi-test/README.md
- projects/portal/editions/ununifi/launch/ununifi-test/firebase-hosting/config.js
> feat: new test net (ununifi-test-v1)

- projects/explorer/src/app/pages/proposals/proposal/proposal.component.html
- projects/explorer/src/app/pages/proposals/proposal/proposal.component.ts
- projects/explorer/src/app/pages/proposals/proposals.component.html
- projects/explorer/src/app/pages/proposals/proposals.component.ts
- projects/explorer/src/app/utils/tx-parser.ts
- projects/explorer/src/app/views/proposals/proposal/proposal.component.html
- projects/explorer/src/app/views/proposals/proposal/proposal.component.ts
- projects/explorer/src/app/views/proposals/proposals.component.html
- projects/explorer/src/app/views/proposals/proposals.component.ts
- projects/portal/src/app/pages/dialogs/vote/deposit-form-dialog/deposit-form-dialog.component.html
- projects/portal/src/app/pages/dialogs/vote/deposit-form-dialog/deposit-form-dialog.component.ts
- projects/portal/src/app/pages/dialogs/vote/vote-form-dialog/vote-form-dialog.component.html
- projects/portal/src/app/pages/dialogs/vote/vote-form-dialog/vote-form-dialog.component.ts
- projects/portal/src/app/pages/vote/proposals/proposal/proposal.component.html
- projects/portal/src/app/pages/vote/proposals/proposal/proposal.component.ts
- projects/portal/src/app/pages/vote/proposals/proposals.component.html
- projects/portal/src/app/pages/vote/proposals/proposals.component.ts
- projects/portal/src/app/views/dialogs/vote/deposit/deposit-form-dialog.component.html
- projects/portal/src/app/views/dialogs/vote/deposit/deposit-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/vote/vote/vote-form-dialog.component.html
- projects/portal/src/app/views/dialogs/vote/vote/vote-form-dialog.component.ts
- projects/portal/src/app/views/vote/proposals/proposal/proposal.component.html
- projects/portal/src/app/views/vote/proposals/proposal/proposal.component.ts
- projects/portal/src/app/views/vote/proposals/proposals.component.html
- projects/portal/src/app/views/vote/proposals/proposals.component.ts
- projects/portal/src/assets/config.js
@YasunoriMATSUOKA cc: @yutaro-elk 
Please review. 🙏 
ProposalContent was parsed in each view component, I fixed it with a common function. (like tx.)
- portal
- explorer
- other
> feat: refactoring proposals contents in portal and explorer

- projects/explorer/README.md
- projects/landing-page-html/README.md
- projects/portal/README.md
@yutaro-elk @mkXultra 
plz review 🙏
> fix: readme about new test net

- package.json
- projects/portal/src/app/pipes/decimals.pipe.spec.ts
- projects/portal/src/app/pipes/floor.pipe.spec.ts
- projects/portal/src/app/pipes/floor.pipe.ts
- projects/portal/src/app/pipes/unit-conversion.pipe.spec.ts
- projects/portal/src/app/pipes/unit-conversion.pipe.ts
@yutaro-elk 
Add three tests, then confirmed that pass all test.
Please review. 🙏 
[https://github.com/UnUniFi/web-apps/issues/258](https://github.com/UnUniFi/web-apps/issues/258)
> feat: Add tests for custom pipes

- projects/portal/src/app/models/faucets/faucet.guard.spec.ts
- projects/portal/src/app/models/faucets/faucet.guard.ts
- projects/portal/src/app/models/keys/key-select.guard.spec.ts
- projects/portal/src/app/models/keys/key-select.guard.ts
- projects/portal/src/app/models/wallets/wallet.guard.spec.ts
- projects/portal/src/app/views/dialogs/wallets/connect-wallet-completed-dialog/connect-wallet-completed-dialog.component.ts
- projects/portal/src/app/views/dialogs/wallets/connect-wallet-start-dialog/connect-wallet-start-dialog.component.ts
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-create-wallet-form-dialog/ununifi-create-wallet-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-mnemonic-form-dialog/ununifi-import-wallet-with-mnemonic-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-private-key-form-dialog/ununifi-import-wallet-with-private-key-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-key-form-dialog/ununifi-key-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-select-wallet-dialog/ununifi-select-wallet-dialog.component.ts
[https://github.com/UnUniFi/web-apps/issues/260](https://github.com/UnUniFi/web-apps/issues/260)
> feat: add tests for Guard services

- projects/marketplace/editions/ununifi/launch/ununifi-8-private-test/firebase-hosting/config.js
- projects/marketplace/editions/ununifi/launch/ununifi-9-beta-test-v1/firebase-hosting/config.js
- projects/marketplace/editions/ununifi/launch/ununifi-alpha-test/firebase-hosting/config.js
- projects/marketplace/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
- projects/marketplace/editions/ununifi/launch/ununifi-test/firebase-hosting/config.js
- projects/marketplace/editions/ununifi/launch/ununifi/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi-8-private-test/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi-9-beta-test-v1/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi/firebase-hosting/config.js
Same fix. [https://github.com/UnUniFi/web-apps/pull/263](https://github.com/UnUniFi/web-apps/pull/263)
I also fixed the Release branch as I felt it was a higher priority.
If unnecessary, please close.
> fix: typo ununufi at release branch (beta-testnet)

- projects/explorer/src/app/pages/proposals/proposals.component.ts
- projects/explorer/src/app/views/proposals/proposal/proposal.component.html
- projects/explorer/src/app/views/proposals/proposal/proposal.component.ts
- projects/explorer/src/app/views/proposals/proposals.component.html
- projects/explorer/src/app/views/proposals/proposals.component.ts
- projects/portal/src/app/pages/vote/proposals/proposals.component.ts
- projects/portal/src/app/views/vote/proposals/proposal/proposal.component.html
- projects/portal/src/app/views/vote/proposals/proposal/proposal.component.ts
- projects/portal/src/app/views/vote/proposals/proposals.component.html
- projects/portal/src/app/views/vote/proposals/proposals.component.ts
close #268
Fixed an issue where the Proposal would not display if cosmosclient.codec.protoJSONToInstance() failed, but the error has not been resolved, so some titles, etc. are not displayed.
Will continue to investigate.
> fix: detail of proposal

- projects/portal/src/app/pages/vote/proposals/proposal/proposal.component.html
- projects/portal/src/app/pages/vote/proposals/proposal/proposal.component.ts
- projects/portal/src/app/pages/vote/proposals/proposal/proposal.usecase.service.spec.ts
- projects/portal/src/app/pages/vote/proposals/proposal/proposal.usecase.service.ts
- projects/portal/src/app/pages/vote/proposals/proposals.component.html
- projects/portal/src/app/pages/vote/proposals/proposals.component.ts
- projects/portal/src/app/pages/vote/proposals/proposals.usecase.service.spec.ts
- projects/portal/src/app/pages/vote/proposals/proposals.usecase.service.ts
> feat: add proposals test

- projects/portal/src/app/pages/delegate/validators/validator/validator.component.ts
- projects/portal/src/app/pages/delegate/validators/validator/validator.usecase.service.spec.ts
- projects/portal/src/app/pages/delegate/validators/validator/validator.usecase.service.ts
- projects/portal/src/app/pages/delegate/validators/validators.component.html
- projects/portal/src/app/pages/delegate/validators/validators.component.ts
- projects/portal/src/app/pages/delegate/validators/validators.usecase.service.spec.ts
- projects/portal/src/app/pages/delegate/validators/validators.usecase.service.ts
- projects/portal/src/app/views/delegate/validators/validators.component.ts
> feat: add delegate test

- projects/portal/src/app/app.module.ts
- projects/portal/src/app/models/cosmos/distribution.application.service.ts
- projects/portal/src/app/models/cosmos/distribution.service.ts
- projects/portal/src/app/pages/balance/balance.component.html
- projects/portal/src/app/pages/balance/balance.component.ts
- projects/portal/src/app/pages/balance/balance.usecase.service.ts
- projects/portal/src/app/pages/dialogs/delegate/withdraw-all-delegator-reward-form-dialog/withdraw-all-delegator-reward-form-dialog.component.html
- projects/portal/src/app/pages/dialogs/delegate/withdraw-all-delegator-reward-form-dialog/withdraw-all-delegator-reward-form-dialog.component.ts
- projects/portal/src/app/pages/dialogs/delegate/withdraw-all-delegator-reward-form-dialog/withdraw-all-delegator-reward-form-dialog.module.ts
- projects/portal/src/app/views/balance/balance.component.html
- projects/portal/src/app/views/balance/balance.component.ts
- projects/portal/src/app/views/cosmos/staking/validators/validator/validator.component.html
- projects/portal/src/app/views/delegate/validators/validators.component.html
- projects/portal/src/app/views/dialogs/delegate/delegate-menu-dialog/delegate-menu-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/withdraw-all-delegator-reward-form-dialog/withdraw-all-delegator-reward-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/withdraw-all-delegator-reward-form-dialog/withdraw-all-delegator-reward-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/delegate/withdraw-all-delegator-reward-form-dialog/withdraw-all-delegator-reward-form-dialog.module.ts
- projects/portal/src/app/views/dialogs/delegate/withdraw-delegator-reward-form-dialog/withdraw-delegator-reward-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/withdraw-validator-commission-form-dialog/withdraw-validator-commission-form-dialog.component.html
Same as #279 
For deployment to beta-test
> Delegator rewards on Balance page

- projects/landing-page-html/index.html
> fix: fix tailwindo version

- projects/portal/src/app/views/dialogs/incentive/create-unit-form-dialog/create-unit-form-dialog.component.ts
- projects/portal/src/app/views/incentive/incentive.component.html
Patch for #316 
Fix ecosystem-incentive MsgRegister
> fix: create incentive unit

- projects/portal/src/app/models/cosmos/bank.query.service.ts
- projects/portal/src/app/models/cosmos/bank.service.ts
need to update cosmos-client because current latest version of cosmos-client don't have rest API wrapper of get denom metadata.
> Denom metadata

- package-lock.json
- package.json
- tailwind.config.js
```
git cherry-pick 7506c04
git cherry-pick c7528a2
```
> feat: daisyui

- projects/portal/src/app/models/cosmos/tx-common.application.service.ts
- projects/portal/src/app/models/cosmos/tx-common.service.ts
Patch for #328 
- Set msg type as any (temporary)
- Add Tx sign (If not, tx will be failed)
@KimuraYu45z Plz check and approve.
> fix: problem of signiture on tx-common 

- projects/landing-page-html/index.html
same as https://github.com/UnUniFi/web-apps/pull/340 for develop
> Fix LP develop

- projects/landing-page-html/index.html
same as https://github.com/UnUniFi/web-apps/pull/340 for release
> Fix LP release

- projects/landing-page-html/index.html
> Fix LP main

- tailwind.config.js
> fix: tailwind.config

- projects/portal/src/styles.css
- projects/shared/src/lib/components/loading-dialog/loading-dialog.component.html
- projects/shared/src/lib/components/loading-dialog/loading-dialog.component.ts
- projects/shared/src/lib/components/loading-dialog/loading-dialog.module.ts
- projects/shared/src/lib/components/loading-dialog/loading-dialog.service.ts
- projects/shared/src/lib/models/ununifi/tx/nft/nft-tx.application.service.ts
- projects/shared/src/lib/views/dialogs/cosmos/tx/common/tx-fee-confirm-dialog/tx-fee-confirm-dialog.component.html
- projects/shared/src/lib/views/dialogs/cosmos/tx/common/tx-fee-confirm-dialog/tx-fee-confirm-dialog.component.ts
> refactor: [loading dialog]Abolish MatDialog and use Dialog of Angular CDK

- projects/portal/src/app/models/keys/key-backup-dialog.service.ts
- projects/portal/src/app/views/keys/key-backup-dialog/key-backup-dialog.component.ts
- portal
- key backup dialog
portal/keys/create
> refactor: [key backup dialog]Abolish MatDialog and use Dialog of Angular CDK

- projects/portal/src/app/models/cosmos/gov.application.service.ts
- projects/portal/src/app/pages/dialogs/vote/deposit-form-dialog/deposit-form-dialog.component.ts
- projects/portal/src/app/pages/dialogs/vote/vote-form-dialog/vote-form-dialog.component.ts
- projects/portal/src/app/views/cosmos/tx-fee-confirm-dialog/tx-fee-confirm-dialog.component.html
- projects/portal/src/app/views/cosmos/tx-fee-confirm-dialog/tx-fee-confirm-dialog.component.ts
- projects/portal/src/app/views/dialogs/vote/deposit/deposit-form-dialog.component.html
- projects/portal/src/app/views/dialogs/vote/vote/vote-form-dialog.component.html
- projects/portal/src/styles.css
- portal
- deposit form dialog
- vote form dialog
portal/vote/proposals/:id
> refactor: [gov app dialog]Abolish MatDialog and use Dialog of Angular CDK

- projects/portal/src/app/models/auctions/auction.application.service.ts
- projects/portal/src/app/models/cdps/cdp.application.service.ts
- projects/portal/src/app/models/cosmos/bank.application.service.ts
- projects/portal/src/app/models/cosmos/slashing.application.service.ts
- projects/portal/src/app/models/cosmos/tx-common.application.service.ts
- projects/portal/src/app/views/cosmos/tx-fee-confirm-dialog/tx-fee-confirm-dialog.component.html
- projects/portal/src/app/views/cosmos/tx-fee-confirm-dialog/tx-fee-confirm-dialog.component.ts
- projects/portal/src/styles.css
- portal
- tx fee confirm dialog
> refactor: [tx fee confirm dialog]Abolish MatDialog and use Dialog of Angular CDK

- projects/portal/src/app/models/keys/key-select-dialog.service.ts
- projects/portal/src/app/views/keys/key-select-dialog/key-select-dialog.component.html
- projects/portal/src/app/views/keys/key-select-dialog/key-select-dialog.component.ts
- projects/portal/src/styles.css
- portal
- key select dialog
portal/keys/gentx
> refactor: [key select dialog]Abolish MatDialog and use Dialog of Angular CDK

- projects/portal/src/app/models/keys/key-delete-dialog.service.ts
- projects/portal/src/app/views/keys/key-delete-confirm-dialog/key-delete-confirm-dialog.component.ts
- projects/portal/src/app/views/keys/key-delete-dialog/key-delete-dialog.component.ts
- projects/portal/src/styles.css
- portal
- key delete dialog
portal/keys/:key_id
> refactor: [key delete dialog]Abolish MatDialog and use Dialog of Angular CDK

- projects/portal/src/app/models/cosmos/distribution.application.service.ts
- projects/portal/src/app/models/cosmos/staking.application.service.ts
- projects/portal/src/app/pages/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.ts
- projects/portal/src/app/pages/dialogs/delegate/delegate-menu-dialog/delegate-menu-dialog.component.ts
- projects/portal/src/app/pages/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.ts
- projects/portal/src/app/pages/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.ts
- projects/portal/src/app/pages/dialogs/delegate/withdraw-all-delegator-reward-form-dialog/withdraw-all-delegator-reward-form-dialog.component.ts
- projects/portal/src/app/pages/dialogs/delegate/withdraw-delegator-reward-form-dialog/withdraw-delegator-reward-form-dialog.component.ts
- projects/portal/src/app/pages/dialogs/delegate/withdraw-validator-commission-form-dialog/withdraw-validator-commission-form-dialog.component.ts
- projects/portal/src/app/pages/staking/staking-routing.module.ts
- projects/portal/src/app/views/cosmos/tx-fee-confirm-dialog/tx-fee-confirm-dialog.component.html
- projects/portal/src/app/views/cosmos/tx-fee-confirm-dialog/tx-fee-confirm-dialog.component.ts
- projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/delegate-menu-dialog/delegate-menu-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/invalid-validator-confirm-dialog/inactive-validator-confirm-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/invalid-validator-confirm-dialog/inactive-validator-confirm-dialog.component.ts
- projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/withdraw-all-delegator-reward-form-dialog/withdraw-all-delegator-reward-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/withdraw-delegator-reward-form-dialog/withdraw-delegator-reward-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/withdraw-validator-commission-form-dialog/withdraw-validator-commission-form-dialog.component.html
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-key-form-dialog/ununifi-key-form-dialog.component.html
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-key-form-dialog/ununifi-key-form-dialog.component.ts
- projects/portal/src/app/views/staking/create-validator-multiple/create-validator-multiple.component.ts
- projects/portal/src/app/views/staking/create-validator-multiple/create-validator-multiple.module.ts
- projects/portal/src/app/views/staking/create-validator-multiple/validator-dialog.html
- projects/portal/src/app/views/staking/edit-validator-multiple/edit-validator-multiple.component.ts
- projects/portal/src/app/views/staking/edit-validator-multiple/edit-validator-multiple.module.ts
- projects/portal/src/app/views/staking/edit-validator-multiple/validator-dialog.html
- projects/portal/src/styles.css
- portal
- validator dialog
- withdraw all delegator reward form dialog
- inactive validator confirm dialog
- withdraw validator commission form dialog
- withdraw delegator reward form dialog
- undelegate form dialog
- redelegate form dialog
- delegate form dialog
- delegate menu dialog
> refactor: [delegate app dialog]Abolish MatDialog and use Dialog of Angular CDK

- projects/explorer/editions/ununifi/launch/ununifi-alpha-test/firebase-hosting/config.js
- projects/explorer/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
- projects/explorer/editions/ununifi/launch/ununifi-stable/firebase-hosting/config.js
- projects/explorer/src/assets/config.js
- projects/portal/editions/ununifi/launch/ununifi-alpha-test/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi-stable/firebase-hosting/config.js
- projects/portal/src/app/pages/faucet/faucet.component.html
- projects/portal/src/app/pages/faucet/faucet.component.ts
- projects/portal/src/app/views/balance/balance.component.html
- projects/portal/src/app/views/faucet/faucet.component.html
- projects/portal/src/app/views/faucet/faucet.component.ts
- projects/portal/src/assets/config.js
New Faucet design & settings
- BTC
- GUU
- USDC
Each max 2 token
> feat: faucet usdc

- projects/explorer/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
> fix: beta test config

- projects/explorer/src/app/views/blocks/block/block.component.html
- projects/explorer/src/app/views/blocks/blocks.component.html
- projects/explorer/src/app/views/cosmos/staking/validators/validator/validator.component.html
- projects/explorer/src/app/views/dashboard/blocks/blocks.component.html
- projects/explorer/src/app/views/dashboard/txs/txs.component.html
- projects/explorer/src/app/views/home/blocks/blocks.component.html
- projects/explorer/src/app/views/monitor/monitor.component.html
- projects/explorer/src/app/views/txs/tx/tx.component.html
- projects/explorer/src/app/views/validators/validator/validator.component.html
- projects/portal/src/app/views/auction/auctions/auction/auction.component.html
- projects/portal/src/app/views/auction/auctions/auction/place-bid/place-bid.component.html
- projects/portal/src/app/views/cosmos/staking/validators/validator/validator.component.html
- projects/portal/src/app/views/delegate/validators/validator/validator.component.html
- projects/portal/src/app/views/delegate/validators/validators.component.html
- projects/portal/src/app/views/derivatives/perpetual-futures/market/market.component.html
- projects/portal/src/app/views/derivatives/pool/pool.component.html
- projects/portal/src/app/views/derivatives/positions/position/perpetual-futures/perpetual-futures.component.html
- projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.html
- projects/portal/src/app/views/home/blocks/blocks.component.html
- projects/portal/src/app/views/mint/cdps/cdp/cdp.component.html
- projects/portal/src/app/views/monitor/monitor.component.html
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/borrow/borrow.component.html
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/borrower-nft.component.html
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/list/list.component.html
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/repay/repay.component.html
- projects/portal/src/app/views/nft-pawnshop/lenders/lender-nfts/lender-nft/lender-nft.component.html
- projects/portal/src/app/views/nft-pawnshop/lenders/lender-nfts/lender-nft/place-bid/place-bid.component.html
- projects/portal/src/app/views/txs/tx/tx.component.html
[feat: long/short color](https://github.com/UnUniFi/web-apps/commit/09af6d2b362bee7d9a1a7eea4f5c26b2390eb5b3)
[feat: mint/burn => buy/sell](https://github.com/UnUniFi/web-apps/commit/d3e4389cf6ed5a5e4f6ce30c54f3eca2334268a7)
[feat: page title](https://github.com/UnUniFi/web-apps/commit/ee53e08c93c1eb644dc3d5672ad9ddd0d35f3a45)
The following issue will be changed later
#375
> chore: word fix

- projects/portal/src/app/app.component.ts
- projects/portal/src/environments/environment.prod.ts
- projects/portal/src/environments/environment.ts
- projects/portal/src/index.html
- projects/portal/src/main.ts
- projects/portal/tsconfig.app.json
> feat: google analytics

- projects/portal/src/app/pages/balance/balance.component.ts
- projects/portal/src/app/views/balance/balance.component.html
- projects/portal/src/app/views/balance/balance.component.ts
> fix: chain ID

- projects/portal/src/app/models/nft-pawnshops/nft-pawnshop.application.service.ts
Tentatively deal with this by multiplying by 10^18
> hotfix: msg listNFT & placeBid Dec

- projects/portal/src/app/views/app.component.html
- projects/portal/src/app/views/balance/balance.component.html
- projects/portal/src/app/views/balance/balance.module.ts
- projects/portal/src/app/views/derivatives/derivatives.component.html
- projects/portal/src/app/views/derivatives/perpetual-futures/market/market.component.html
- projects/portal/src/app/views/derivatives/perpetual-futures/market/market.component.ts
- projects/portal/src/app/views/derivatives/perpetual-futures/perpetual-futures.component.html
- projects/portal/src/app/views/derivatives/pool/pool.component.html
- projects/portal/src/app/views/derivatives/positions/position/perpetual-futures/perpetual-futures.component.html
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/borrow/borrow.component.html
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/borrower-nft.component.html
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/repay/repay.component.html
- projects/portal/src/app/views/nft-pawnshop/lenders/lender-nfts/lender-nft/lender-nft.component.html
- projects/portal/src/app/views/nfts/mint/mint.component.html
#375
New Balance Page (Top Page)
Fixed drawer not closing issue
Not yet tested on mobile
> New design 0321

- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/borrower-nft.component.html
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/repay/repay.component.html
Fixed Repay displayed on NFT status page.
> fix: repay text

- projects/portal/src/app/views/dialogs/nft-pawnshop/nfts-dialog/nfts-dialog.component.html
- projects/portal/src/app/views/nft-pawnshop/lenders/lenders.component.html
#375 
- New Lenders
- New Popup
https://github.com/UnUniFi/web-apps/pull/372#issuecomment-1476311200
It is a white background due to the coexistence of Angular Material and CDK Dialog but it will be improved.
> New Lenders UI

- projects/portal/src/app/views/nft-pawnshop/lenders/lender-nfts/lender-nft/place-bid/place-bid.component.html
Removed settings for POC in PlaceBid page
> hotfix: poc settings

- projects/portal/src/app/views/derivatives/perpetual-futures/market/market.component.html
Change table position if window >=1280px
Improved display on 1440px (modern laptop)
> hotfix: 1440px trading

- projects/landing-page-html/index.html
- projects/portal/src/app/views/derivatives/perpetual-futures/market/market.component.html
> fix: text position

- projects/portal/src/app/app.component.ts
fix https://github.com/UnUniFi/lab-test/issues/78 issue
> hotfix: node change navigation

- projects/portal/src/app/models/cosmos/tx-common.service.ts
- projects/portal/src/app/models/incentives/incentive.application.service.ts
- projects/portal/src/app/models/incentives/incentive.service.ts
- projects/portal/src/app/models/nft-pawnshops/nft-pawnshop.application.service.ts
- projects/portal/src/app/models/nft-pawnshops/nft-pawnshop.service.ts
- projects/portal/src/app/views/dialogs/incentive/create-unit-form-dialog/create-unit-form-dialog.component.ts
Add number => *10^18 & toString() function
NFT Bacled Loan & Ecosystem Incentive applied but Derivatives left #421
> feat: dec string

- projects/portal/src/app/models/cosmos/bank.application.service.ts
- projects/portal/src/app/models/cosmos/gov.application.service.ts
- projects/portal/src/app/models/cosmos/staking.application.service.ts
- projects/portal/src/app/models/derivatives/derivatives.application.service.ts
- projects/portal/src/app/models/incentives/incentive.application.service.ts
- projects/portal/src/app/models/nft-pawnshops/nft-pawnshop.application.service.ts
close https://github.com/UnUniFi/lab-test/issues/82
Added reloading for no screen transition after Tx on some pages.
> fix: location reload

- projects/portal/src/app/views/nft-pawnshop/lenders/lenders.component.html
- projects/portal/src/app/views/nft-pawnshop/lenders/lenders.component.ts
Add toggle for NFT Search menu
Status display of bidding under consideration.
https://github.com/UnUniFi/lab-test/issues/87
> feat: search menu toggle

- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/borrow/borrow.component.html
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/borrower-nft.component.html
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/list/list.component.html
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/repay/repay.component.html
- projects/portal/src/app/views/nft-pawnshop/lenders/lender-nfts/lender-nft/lender-nft.component.html
- projects/portal/src/app/views/nft-pawnshop/lenders/lender-nfts/lender-nft/place-bid/place-bid.component.html
> hotfix: nft image

- projects/portal/src/app/views/dialogs/incentive/create-unit-form-dialog/create-unit-form-dialog.component.css
- projects/portal/src/app/views/dialogs/incentive/create-unit-form-dialog/create-unit-form-dialog.component.html
- projects/portal/src/app/views/dialogs/incentive/create-unit-form-dialog/create-unit-form-dialog.module.ts
- projects/portal/src/app/views/dialogs/incentive/withdraw-incentive-all-rewards-form-dialog/withdraw-incentive-all-rewards-form-dialog.component.css
- projects/portal/src/app/views/dialogs/incentive/withdraw-incentive-all-rewards-form-dialog/withdraw-incentive-all-rewards-form-dialog.component.html
- projects/portal/src/app/views/dialogs/incentive/withdraw-incentive-all-rewards-form-dialog/withdraw-incentive-all-rewards-form-dialog.module.ts
- projects/portal/src/app/views/dialogs/incentive/withdraw-incentive-reward-form-dialog/withdraw-incentive-reward-form-dialog.component.css
- projects/portal/src/app/views/dialogs/incentive/withdraw-incentive-reward-form-dialog/withdraw-incentive-reward-form-dialog.component.html
- projects/portal/src/app/views/dialogs/incentive/withdraw-incentive-reward-form-dialog/withdraw-incentive-reward-form-dialog.module.ts
- angular/material -> daisy ui
- Delete angular/material
Check the results of DaysiUI support in the following UI.
If there is any part of the design that is not good looking, please point it out.
- incentive
- create-unit-form-dialog
- withdraw-incentive-all-rewards-form-dialog
- withdraw-incentive-reward-form-dialog
The following fixes have already been addressed in "refactor/wallet-app-use-daisyui" and are not included in this branch.
https://github.com/UnUniFi/web-apps/issues/390
- dialogs with Daisy UI's Card
- Remove CSS from cdk-dialog-container
``` css
/* cdk-dialog-container {
display: block;
color: #000000 !important;
background: #ffffff !important;
border-radius: 4px;
padding: 24px;
} */
```
> unify incentive dialog to CDK+Daisy UI

- package-lock.json
- package.json
- projects/portal/src/app/models/ununifi/yield-aggregator.query.service.ts
- projects/portal/src/app/models/ununifi/yield-aggregator.service.ts
- projects/portal/src/app/pages/yield-aggregator/vaults/vault/vault.component.ts
- projects/portal/src/app/views/yield-aggregator/vaults/vault/vault.component.html
- projects/portal/src/app/views/yield-aggregator/vaults/vault/vault.component.ts
Adaptation to new chain
Merge after backend update (03/31 11:00-12:00)
> feat: update ununifi-ts rc6

- .github/workflows/cr.yml
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/list/list.component.html
GPT works only PR opened, reopened
> chore: disable gpt

- projects/portal/src/app/pages/apps/app-derivatives/app-derivatives.component.html
- projects/portal/src/app/pages/apps/app-derivatives/app-derivatives.component.ts
- projects/portal/src/app/pages/apps/app-nft-backed-loans/app-nft-backed-loans.component.html
- projects/portal/src/app/pages/apps/app-nft-backed-loans/app-nft-backed-loans.component.ts
- projects/portal/src/app/views/apps/app-derivatives/app-derivatives.component.html
- projects/portal/src/app/views/apps/app-derivatives/app-derivatives.component.ts
- projects/portal/src/app/views/apps/app-nft-backed-loans/app-nft-backed-loans.component.html
- projects/portal/src/app/views/apps/app-nft-backed-loans/app-nft-backed-loans.component.ts
- projects/portal/src/app/views/apps/app-utils/app-utils.component.html
- projects/portal/src/app/views/apps/app-utils/app-utils.component.ts
- projects/portal/src/app/views/balance/balance.component.html
- projects/portal/src/app/views/tools/app-tool/app-tool.component.ts
- projects/portal/src/app/views/tools/node-tool/node-tool.component.html
Only on mobile will all pages show the hamburger and display the following
(tablet or laptop displays are not changed)
- Utils
- NFT-Fi
- Derivatives
> feat: mobile UX & UI

- projects/portal/src/app/pages/vote/proposals/proposal/proposal.component.ts
- projects/portal/src/app/pages/vote/proposals/proposals.component.ts
- projects/portal/src/app/views/delegate/validators/validator/validator.component.html
- projects/portal/src/app/views/delegate/validators/validator/validator.component.ts
- projects/portal/src/app/views/delegate/validators/validator/validator.module.ts
- projects/portal/src/app/views/delegate/validators/validators.component.html
- projects/portal/src/app/views/delegate/validators/validators.component.ts
- projects/portal/src/app/views/vote/proposals/proposal/proposal.component.html
- projects/portal/src/app/views/vote/proposals/proposal/proposal.component.ts
- projects/portal/src/app/views/vote/proposals/proposal/proposal.module.ts
- projects/portal/src/app/views/vote/proposals/proposals.component.html
- projects/portal/src/app/views/vote/proposals/proposals.component.ts
Support for Daisy UI
- Validators list
- Validator detail
- Proposals list
- Proposal detail
> feat: Daisy UI (Delegate & Vote)

- projects/portal/src/app/models/cosmos/bank.application.service.ts
- projects/portal/src/app/models/cosmos/bank.model.ts
- projects/portal/src/app/models/cosmos/bank.service.ts
- projects/portal/src/app/pages/balance/balance-routing.module.ts
- projects/portal/src/app/pages/balance/balance.module.ts
- projects/portal/src/app/pages/balance/send/send.component.html
- projects/portal/src/app/pages/balance/send/send.component.ts
- projects/portal/src/app/views/apps/app-utils/app-utils.component.html
- projects/portal/src/app/views/balance/send/send.component.html
- projects/portal/src/app/views/balance/send/send.component.ts
- projects/portal/src/app/views/balance/send/send.module.ts
Leave existing cosmos/bank/send and create new /send
Select from the list of tokens you have and the Amount input and Available Balance will be displayed.
> feat: new bank send

- projects/portal/src/app/models/wallets/wallet.application.service.ts
- projects/portal/src/app/models/wallets/wallet.infrastructure.service.ts
- projects/portal/src/app/models/wallets/wallet.service.ts
- projects/portal/src/app/pages/tools/wallet-tool/wallet-tool.component.html
- projects/portal/src/app/pages/tools/wallet-tool/wallet-tool.component.ts
- projects/portal/src/app/views/tools/wallet-tool/wallet-tool.component.html
- projects/portal/src/app/views/tools/wallet-tool/wallet-tool.component.ts
- projects/portal/src/app/views/tools/wallet-tool/wallet-tool.module.ts
https://github.com/UnUniFi/lab-test/issues/93
Impl wallet dropdown & Disconnect feature
Balance will be displayed for GUUs only. Will be determined tomorrow.
> feat: Wallet dialog

- projects/portal/src/app/views/derivatives/perpetual-futures/market/market.component.html
- projects/portal/src/app/views/derivatives/positions/position/perpetual-futures/perpetual-futures.component.html
- projects/portal/src/app/views/faucet/faucet.component.html
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower/borrower.component.html
- projects/portal/src/app/views/nft-pawnshop/lenders/lender/lender.component.html
- projects/portal/src/app/views/nft-pawnshop/lenders/lenders.component.html
- projects/portal/src/app/views/vote/proposals/proposals.component.html
Improved display defects discovered as a result of checking on a real device.
> [Release] fix: mobile UI

- projects/landing-page-html/index.html
- projects/landing-page-html/main.css
> feat: add disclaimer

- projects/explorer/editions/ununifi/launch/ununifi-alpha-test/firebase-hosting/config.js
- projects/explorer/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
- projects/explorer/editions/ununifi/launch/ununifi-stable/firebase-hosting/config.js
- projects/explorer/src/assets/config.js
- projects/portal/editions/ununifi/launch/ununifi-alpha-test/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi-stable/firebase-hosting/config.js
- projects/portal/src/app/views/derivatives/perpetual-futures/market/market.component.html
- projects/portal/src/assets/config.js
Fix dev port https 3032 => 3040
Derivatives widget heght 480px => 450px (The iPhone screen will fit either way.)
> chore: dev port&derivatives height

- projects/portal/src/app/views/balance/send/send.component.html
- projects/portal/src/app/views/derivatives/perpetual-futures/market/market.component.html
- projects/portal/src/app/views/derivatives/pool/pool.component.html
- projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/delegate-menu-dialog/delegate-menu-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/incentive/create-unit-form-dialog/create-unit-form-dialog.component.html
- projects/portal/src/app/views/dialogs/incentive/withdraw-incentive-all-rewards-form-dialog/withdraw-incentive-all-rewards-form-dialog.component.html
- projects/portal/src/app/views/dialogs/incentive/withdraw-incentive-reward-form-dialog/withdraw-incentive-reward-form-dialog.component.html
- projects/portal/src/app/views/faucet/faucet.component.html
- projects/portal/src/app/views/nft-pawnshop/lenders/lender-nfts/lender-nft/place-bid/place-bid.component.html
- projects/portal/src/app/views/nfts/mint/mint.component.html
Add e.g. in placeholders
Fix Delegate menu dialog
Fix some Button size
> chore: ui fix

- projects/portal/src/app/views/balance/send/send.component.html
- projects/portal/src/app/views/derivatives/perpetual-futures/market/market.component.html
- projects/portal/src/app/views/derivatives/pool/pool.component.html
- projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/delegate-menu-dialog/delegate-menu-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/incentive/create-unit-form-dialog/create-unit-form-dialog.component.html
- projects/portal/src/app/views/dialogs/incentive/withdraw-incentive-all-rewards-form-dialog/withdraw-incentive-all-rewards-form-dialog.component.html
- projects/portal/src/app/views/dialogs/incentive/withdraw-incentive-reward-form-dialog/withdraw-incentive-reward-form-dialog.component.html
- projects/portal/src/app/views/faucet/faucet.component.html
- projects/portal/src/app/views/nft-pawnshop/lenders/lender-nfts/lender-nft/place-bid/place-bid.component.html
- projects/portal/src/app/views/nfts/mint/mint.component.html
> [Release] chore: ui fix

- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/borrow/borrow.component.html
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/borrow/borrow.module.ts
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/borrower-nft.component.html
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/list/list.component.html
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/list/list.module.ts
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/repay/repay.component.html
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/repay/repay.module.ts
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower/borrower.component.html
- projects/portal/src/app/views/nft-pawnshop/lenders/lender-nfts/lender-nft/lender-nft.component.html
- projects/portal/src/app/views/nft-pawnshop/lenders/lender-nfts/lender-nft/place-bid/place-bid.component.html
- projects/portal/src/app/views/nft-pawnshop/lenders/lender/lender.component.html
- projects/portal/src/app/views/nft-pawnshop/lenders/lenders.component.html
Use breadcrumbs in NFT-Backed Loan module
https://daisyui.com/components/breadcrumbs/
> feat: NFT breadcrumbs

- projects/portal/src/app/views/cosmos/bank/send/send.component.html
- projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/vote/deposit/deposit-form-dialog.component.html
- projects/portal/src/app/views/dialogs/vote/deposit/deposit-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/vote/deposit/deposit-form-dialog.module.ts
- projects/portal/src/app/views/dialogs/vote/vote/vote-form-dialog.component.html
> Fix: vote form&amount

- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/borrow/borrow.component.html
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/borrow/borrow.module.ts
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/borrower-nft.component.html
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/list/list.component.html
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/list/list.module.ts
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/repay/repay.component.html
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/repay/repay.module.ts
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower/borrower.component.html
- projects/portal/src/app/views/nft-pawnshop/lenders/lender-nfts/lender-nft/lender-nft.component.html
- projects/portal/src/app/views/nft-pawnshop/lenders/lender-nfts/lender-nft/place-bid/place-bid.component.html
- projects/portal/src/app/views/nft-pawnshop/lenders/lender/lender.component.html
- projects/portal/src/app/views/nft-pawnshop/lenders/lenders.component.html
> [Release] feat: NFT breadcrumbs

- projects/portal/src/app/pages/delegate/validators/validator/validator.component.html
- projects/portal/src/app/pages/delegate/validators/validator/validator.component.ts
- projects/portal/src/app/views/delegate/validators/validator/validator.component.html
- projects/portal/src/app/views/delegate/validators/validator/validator.component.ts
- projects/portal/src/app/views/delegate/validators/validators.component.html
- projects/portal/src/app/views/derivatives/derivatives.component.html
- projects/portal/src/app/views/derivatives/perpetual-futures/market/market.component.html
- projects/portal/src/app/views/derivatives/perpetual-futures/perpetual-futures.component.html
- projects/portal/src/app/views/derivatives/pool/pool.component.html
- projects/portal/src/app/views/derivatives/positions/position/position.component.html
- projects/portal/src/app/views/derivatives/positions/positions.component.html
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower/borrower.component.html
- projects/portal/src/app/views/nft-pawnshop/lenders/lender/lender.component.html
- projects/portal/src/app/views/nft-pawnshop/lenders/lenders.component.html
- projects/portal/src/app/views/nft-pawnshop/nft-pawnshop.component.html
- projects/portal/src/app/views/vote/proposals/proposal/proposal.component.html
- projects/portal/src/app/views/vote/proposals/proposals.component.html
[fix top page ui](https://github.com/UnUniFi/web-apps/commit/c8b20e63fd9cc53d4648ba7a57780b802e36595e)
[add breadcrumbs derivatives](https://github.com/UnUniFi/web-apps/commit/b18e32201d003ee996e42a7325d1265a6b6e5ec7)
some UI fix
@KimuraYu45z The transparent background image on the top page is not a good UI, so only the base color was changed.
> feat: improve top page & some refactor

- projects/portal/src/app/pages/delegate/validators/validator/validator.component.html
- projects/portal/src/app/pages/delegate/validators/validator/validator.component.ts
- projects/portal/src/app/views/delegate/validators/validator/validator.component.html
- projects/portal/src/app/views/delegate/validators/validator/validator.component.ts
- projects/portal/src/app/views/delegate/validators/validators.component.html
- projects/portal/src/app/views/derivatives/derivatives.component.html
- projects/portal/src/app/views/derivatives/perpetual-futures/market/market.component.html
- projects/portal/src/app/views/derivatives/perpetual-futures/perpetual-futures.component.html
- projects/portal/src/app/views/derivatives/pool/pool.component.html
- projects/portal/src/app/views/derivatives/positions/position/position.component.html
- projects/portal/src/app/views/derivatives/positions/positions.component.html
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower/borrower.component.html
- projects/portal/src/app/views/nft-pawnshop/lenders/lender/lender.component.html
- projects/portal/src/app/views/nft-pawnshop/lenders/lenders.component.html
- projects/portal/src/app/views/nft-pawnshop/nft-pawnshop.component.html
- projects/portal/src/app/views/vote/proposals/proposal/proposal.component.html
- projects/portal/src/app/views/vote/proposals/proposals.component.html
> [Release]feat: improve top page & some refactor

- projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/incentive/create-unit-form-dialog/create-unit-form-dialog.component.html
- projects/portal/src/app/views/dialogs/incentive/create-unit-form-dialog/create-unit-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/incentive/withdraw-incentive-all-rewards-form-dialog/withdraw-incentive-all-rewards-form-dialog.component.html
- projects/portal/src/app/views/dialogs/incentive/withdraw-incentive-reward-form-dialog/withdraw-incentive-reward-form-dialog.component.html
- projects/portal/src/app/views/dialogs/vote/deposit/deposit-form-dialog.component.html
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-backup-private-key-wizard-dialog/ununifi-backup-private-key-wizard-dialog.component.html
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-create-wallet-form-dialog/ununifi-create-wallet-form-dialog.component.html
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-mnemonic-form-dialog/ununifi-import-wallet-with-mnemonic-form-dialog.component.html
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-private-key-form-dialog/ununifi-import-wallet-with-private-key-form-dialog.component.html
- projects/portal/src/app/views/faucet/faucet.component.html
- projects/portal/src/app/views/incentive/incentive.component.html
- projects/portal/src/app/views/incentive/incentive.module.ts
- projects/portal/src/app/views/incentive/units/unit/unit.component.html
- projects/portal/src/app/views/nfts/mint/mint.component.html
Improve Ecosystem Incetive UI with Daisy UI
> feat: Ecosystem Incentive UI

- projects/portal/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
- projects/portal/src/app/models/developer.service.ts
- projects/portal/src/app/pages/apps/app-derivatives/app-derivatives.component.ts
- projects/portal/src/app/pages/apps/app-nft-backed-loans/app-nft-backed-loans.component.ts
- projects/portal/src/app/pages/apps/app-utils/app-utils.component.ts
Enable developer node option on Lab net
Available only 5 dev account
> feat: developer tab

- projects/portal/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
- projects/portal/src/app/models/developer.service.ts
- projects/portal/src/app/pages/apps/app-derivatives/app-derivatives.component.ts
- projects/portal/src/app/pages/apps/app-nft-backed-loans/app-nft-backed-loans.component.ts
- projects/portal/src/app/pages/apps/app-utils/app-utils.component.ts
> feat: developer tab 

- projects/portal/src/app/views/tools/wallet-tool/wallet-tool.component.ts
Add EventListener for changing key store in Keplr.
- It works only when Portal is open.
> feat: detected change keplr key

- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/borrow/borrow.component.ts
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/repay/repay.component.ts
- projects/portal/src/app/views/nft-pawnshop/lenders/lender-nfts/lender-nft/place-bid/place-bid.component.html
- projects/portal/src/app/views/nft-pawnshop/lenders/lender-nfts/lender-nft/place-bid/place-bid.component.ts
> add: NFT-Fi Error handling

- projects/explorer/src/app/models/config.service.ts
- projects/portal/src/app/models/config.service.ts
save selected node indfo to local strage
> feat: save selected node

- projects/explorer/src/app/pages/tools/node-tool/node-tool.component.html
- projects/explorer/src/app/pages/tools/node-tool/node-tool.component.ts
- projects/explorer/src/app/pages/tools/node-tool/node-tool.module.ts
- projects/explorer/src/app/pages/tools/search-tool/search-tool.component.html
- projects/explorer/src/app/pages/tools/search-tool/search-tool.component.ts
- projects/explorer/src/app/pages/tools/search-tool/search-tool.module.ts
- projects/explorer/src/app/views/app.component.html
- projects/explorer/src/app/views/tools/node-tool/node-tool.component.html
- projects/explorer/src/app/views/tools/node-tool/node-tool.component.ts
- projects/explorer/src/app/views/tools/node-tool/node-tool.module.ts
- projects/explorer/src/app/views/tools/search-tool/search-tool.component.html
- projects/explorer/src/app/views/tools/search-tool/search-tool.component.ts
- projects/explorer/src/app/views/tools/search-tool/search-tool.module.ts
- projects/explorer/src/app/views/view.module.ts
- Add node tool to Explorer
- Add Searchbar to Explorer (Did not check)
> feat: explorer tools

- projects/explorer/src/app/pages/proposals/proposals.component.ts
- projects/explorer/src/app/pipes/coin-amount.pipe.ts
- projects/explorer/src/app/pipes/pipes.module.ts
- projects/explorer/src/app/views/blocks/blocks.component.html
- projects/explorer/src/app/views/dashboard/blocks/blocks.component.html
- projects/explorer/src/app/views/dashboard/validators/validators.component.html
- projects/explorer/src/app/views/proposals/proposals.component.html
- projects/explorer/src/app/views/proposals/proposals.component.ts
- projects/explorer/src/app/views/validators/validators.component.html
- projects/explorer/src/app/views/validators/validators.component.ts
- projects/portal/src/app/views/vote/proposals/proposals.component.html
- New Validator LIst UI
- New Proposal UI (& for Portal fix)
- New Blocks UI
- Fix Dashboard Pointor
> feat: explorer daisy page

- projects/portal/src/app/models/cosmos/bank.query.service.ts
- projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.ts
> Hotfix: delagate denom

- .gitignore
- README.md
- angular.json
- package.json
Add feature for https debug
for detail, README.md
> feat: https localhost setting

- projects/portal/src/app/models/wallets/wallet.guard.spec.ts
- projects/portal/src/app/models/wallets/wallet.guard.ts
- projects/portal/src/app/pages/balance/balance-routing.module.ts
- projects/portal/src/app/pages/incentive/incentive-routing.module.ts
- projects/portal/src/app/pages/nft-pawnshop/nft-pawnshop-routing.module.ts
- projects/portal/src/app/pages/yield-aggregator/strategies/strategies.component.html
- projects/portal/src/app/pages/yield-aggregator/strategies/strategies.component.ts
- projects/portal/src/app/pages/yield-aggregator/vaults/create/create.component.html
- projects/portal/src/app/pages/yield-aggregator/vaults/create/create.component.ts
- projects/portal/src/app/pages/yield-aggregator/yield-aggregator-routing.module.ts
- projects/portal/src/app/views/apps/app-yield-aggregator/app-yield-aggregator.component.html
- projects/portal/src/app/views/balance/send/send.component.html
- projects/portal/src/app/views/yield-aggregator/strategies/strategies.component.html
- projects/portal/src/app/views/yield-aggregator/strategies/strategies.component.ts
- projects/portal/src/app/views/yield-aggregator/strategies/strategies.module.ts
- projects/portal/src/app/views/yield-aggregator/vaults/create/create.component.html
- projects/portal/src/app/views/yield-aggregator/vaults/create/create.component.ts
Only the currency in which the strategy exists can now be selected. (Create Vault)
Add guide message for https://github.com/UnUniFi/lab-test/issues/109
> feat: select asset by available strategies & some guide message

- projects/explorer/src/app/pages/dashboard/txs/txs.component.html
- projects/explorer/src/app/pages/dashboard/txs/txs.component.ts
- projects/explorer/src/app/pages/txs/txs.component.html
- projects/explorer/src/app/pages/txs/txs.component.ts
- projects/explorer/src/app/views/dashboard/txs/txs.component.html
- projects/explorer/src/app/views/dashboard/txs/txs.component.ts
- projects/explorer/src/app/views/dashboard/txs/txs.module.ts
- projects/explorer/src/app/views/txs/txs.component.html
- projects/explorer/src/app/views/txs/txs.component.ts
- projects/explorer/src/app/views/txs/txs.module.ts
Fix Txs list function
Improved dashboard operation speed
Shortage txType by feedback https://github.com/UnUniFi/lab-test/issues/110
> hotfix: txs list

- projects/portal/src/app/views/tools/app-tool/app-tool.component.ts
> chore: dapps sorting order

- projects/explorer/src/app/pages/proposals/proposal/proposal.component.html
- projects/explorer/src/app/pages/proposals/proposal/proposal.component.ts
- projects/explorer/src/app/pages/proposals/proposals.component.html
- projects/explorer/src/app/pages/proposals/proposals.component.ts
- projects/explorer/src/app/views/dashboard/blocks/blocks.component.html
- projects/explorer/src/app/views/dashboard/dashboard.component.html
- projects/explorer/src/app/views/dashboard/txs/txs.component.html
- projects/explorer/src/app/views/dashboard/validators/validators.component.html
- projects/explorer/src/app/views/proposals/proposal/proposal.component.html
- projects/explorer/src/app/views/proposals/proposal/proposal.component.ts
- projects/explorer/src/app/views/proposals/proposal/proposal.module.ts
- projects/explorer/src/app/views/proposals/proposals.component.html
- projects/explorer/src/app/views/proposals/proposals.component.ts
- projects/explorer/src/app/views/txs/txs.component.html
- projects/portal/src/app/pages/vote/proposals/proposal/proposal.component.ts
- projects/portal/src/app/pages/vote/proposals/proposals.component.html
- projects/portal/src/app/pages/vote/proposals/proposals.component.ts
- projects/portal/src/app/views/vote/proposals/proposal/proposal.component.html
- projects/portal/src/app/views/vote/proposals/proposal/proposal.component.ts
- projects/portal/src/app/views/vote/proposals/proposals.component.html
- projects/portal/src/app/views/vote/proposals/proposals.component.ts
Fix proposal detail on v0.47 sdk
- Add proposal detail table
- Delete unused codes
- Improve mobile display
> fix: proposal-detail

- .github/workflows/cr.yml
- package-lock.json
- package.json
- projects/explorer/editions/ununifi/launch/ununifi/firebase-hosting/config.js
- projects/landing-page-html/index.html
- projects/portal/editions/ununifi/launch/ununifi/firebase-hosting/config.js
- projects/portal/src/app/views/material.module.ts
> Main develop's change

- .github/workflows/cr.yml
- package-lock.json
- package.json
- projects/explorer/editions/ununifi/launch/ununifi/firebase-hosting/config.js
- projects/landing-page-html/index.html
- projects/portal/editions/ununifi/launch/ununifi/firebase-hosting/config.js
- projects/portal/src/app/views/material.module.ts
- Decode Block proposer & Block Hash 
- Fix Neukind node
> Release develop's change

- package-lock.json
- package.json
- projects/portal/src/app/models/cosmos/staking.service.ts
> fix: delete-bignumber.js

- package-lock.json
- package.json
- projects/portal/src/app/models/cosmos/staking.service.ts
- projects/portal/src/app/models/incentives/incentive.application.service.ts
- projects/portal/src/app/models/incentives/incentive.query.service.ts
- projects/portal/src/app/models/incentives/incentive.service.ts
- projects/portal/src/app/models/nft-mints/nft-mint.service.ts
- projects/portal/src/app/models/nft-pawnshops/nft-pawnshop.application.service.ts
- projects/portal/src/app/models/nft-pawnshops/nft-pawnshop.model.ts
- projects/portal/src/app/models/nft-pawnshops/nft-pawnshop.query.service.ts
- projects/portal/src/app/models/nft-pawnshops/nft-pawnshop.service.ts
- projects/portal/src/app/models/yield-aggregators/yield-aggregator.query.service.ts
- projects/portal/src/app/pages/dialogs/incentive/create-unit-form-dialog/create-unit-form-dialog.component.ts
- projects/portal/src/app/pages/incentive/incentive.component.ts
- projects/portal/src/app/pages/incentive/units/unit/unit.component.ts
- projects/portal/src/app/pages/nft-pawnshop/nft-pawnshop.component.ts
- projects/portal/src/app/views/dialogs/incentive/create-unit-form-dialog/create-unit-form-dialog.component.ts
- projects/portal/src/app/views/incentive/units/unit/unit.component.html
- projects/portal/src/app/views/incentive/units/unit/unit.component.ts
- projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/list/list.component.ts
- projects/portal/src/app/views/nft-pawnshop/nft-pawnshop.component.ts
Compatible with ununifi-client v2.2.0
merge `main` after v2.2.0 update
> feat: rename-module & type

- projects/portal/src/app/models/wallets/keplr/keplr.infrastructure.service.ts
- projects/portal/src/app/models/wallets/keplr/keplr.service.ts
- projects/portal/src/app/pages/tools/wallet-tool/wallet-tool.component.html
- projects/portal/src/app/pages/tools/wallet-tool/wallet-tool.component.ts
- projects/portal/src/app/views/tools/wallet-tool/wallet-tool.component.ts
close #19
Detects Keplr wallet changes made when Portal is not open and automatically logout.
> feat: detected mismatch keplr wallet

- projects/portal/editions/ununifi/launch/ununifi-test/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi/firebase-hosting/config.js
Merge after backend Faucet setup
> fix: faucet setting

- projects/explorer/src/app/views/txs/tx/tx-common/msg-fund-community-pool/msg-fund-community-pool.component.html
- projects/explorer/src/app/views/txs/tx/tx-common/msg-set-withdraw-address/msg-set-withdraw-address.component.html
- projects/explorer/src/app/views/txs/tx/tx-common/msg-submit-proposal/msg-submit-proposal.component.html
- projects/explorer/src/app/views/txs/tx/tx-common/msg-undelegate/msg-undelegate.component.html
- projects/explorer/src/app/views/txs/tx/tx-common/msg-vote-weighted/msg-vote-weighted.component.html
- projects/explorer/src/app/views/txs/tx/tx-common/msg-withdraw-deledator-reward/msg-withdraw-deledator-reward.component.html
- projects/explorer/src/app/views/txs/tx/tx-common/msg-withdraw-validator-commission/msg-withdraw-validator-commission.component.html
> Explorer msg daisy

- projects/explorer/editions/ununifi/launch/ununifi-test/firebase-hosting/config.js
- projects/explorer/src/app/views/proposals/proposal/proposal.component.html
- projects/portal/editions/ununifi/launch/ununifi-test/firebase-hosting/config.js
- projects/portal/src/app/views/vote/proposals/proposal/proposal.component.html
Fixed an issue where the Proposal voting details were displayed as UNSPECIFIED
Fixed problem with non-GUU Faucet being displayed on testnet
> Fix frontend UI

- package-lock.json
- package.json
- projects/portal/src/app/models/yield-aggregators/yield-aggregator.query.service.ts
- projects/portal/src/app/models/yield-aggregators/yield-aggregator.service.ts
- projects/portal/src/app/pages/yieldaggregator/strategies/strategies.component.ts
- projects/portal/src/app/pages/yieldaggregator/strategies/strategy/strategy.component.ts
- projects/portal/src/app/pages/yieldaggregator/vaults/create/create.component.ts
- projects/portal/src/app/pages/yieldaggregator/vaults/owner/owner.component.ts
- projects/portal/src/app/pages/yieldaggregator/vaults/vault/vault.component.html
- projects/portal/src/app/pages/yieldaggregator/vaults/vault/vault.component.ts
- projects/portal/src/app/pages/yieldaggregator/vaults/vaults.component.ts
- projects/portal/src/app/pages/yieldaggregator/yield-aggregator.component.ts
- projects/portal/src/app/views/yieldaggregator/strategies/strategies.component.html
- projects/portal/src/app/views/yieldaggregator/strategies/strategy/strategy.component.html
- projects/portal/src/app/views/yieldaggregator/vaults/create/create.component.html
- projects/portal/src/app/views/yieldaggregator/vaults/create/create.component.ts
- projects/portal/src/app/views/yieldaggregator/vaults/owner/owner.component.html
- projects/portal/src/app/views/yieldaggregator/vaults/vault/vault.component.html
- projects/portal/src/app/views/yieldaggregator/vaults/vault/vault.component.ts
- projects/portal/src/app/views/yieldaggregator/vaults/vaults.component.html
- Compatible with v3.2.2 https://github.com/UnUniFi/chain/releases/tag/v3.2.2
- Change in get method (Vault list's total deposit value )
- Add the detail of Estimation redeem amount
- redeem = total - fee
> v3.2.2-iya-fix

- package-lock.json
- package.json
- projects/portal/src/app/models/incentives/incentive.query.service.ts
- projects/portal/src/app/models/nft-pawnshops/nft-pawnshop.query.service.ts
- projects/portal/src/app/pages/dialogs/incentive/withdraw-incentive-all-rewards-form-dialog/withdraw-incentive-all-rewards-form-dialog.component.ts
- projects/portal/src/app/pages/dialogs/incentive/withdraw-incentive-reward-form-dialog/withdraw-incentive-reward-form-dialog.component.html
- projects/portal/src/app/pages/dialogs/incentive/withdraw-incentive-reward-form-dialog/withdraw-incentive-reward-form-dialog.component.ts
- projects/portal/src/app/pages/ecosystemincentive/incentive.component.ts
- projects/portal/src/app/pages/nftbackedloan/borrowers/borrow/borrow.component.ts
- projects/portal/src/app/pages/nftbackedloan/borrowers/repay/repay.component.ts
- projects/portal/src/app/pages/nftbackedloan/lenders/lender/lender.component.ts
- projects/portal/src/app/pages/nftbackedloan/lenders/lenders.component.ts
- projects/portal/src/app/pages/nftbackedloan/lenders/place-bid/place-bid.component.ts
- projects/portal/src/app/pages/nftbackedloan/nfts/class/nft/nft.component.ts
- projects/portal/src/app/views/dialogs/incentive/withdraw-incentive-all-rewards-form-dialog/withdraw-incentive-all-rewards-form-dialog.component.html
- projects/portal/src/app/views/dialogs/incentive/withdraw-incentive-all-rewards-form-dialog/withdraw-incentive-all-rewards-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/incentive/withdraw-incentive-reward-form-dialog/withdraw-incentive-reward-form-dialog.component.html
- projects/portal/src/app/views/dialogs/incentive/withdraw-incentive-reward-form-dialog/withdraw-incentive-reward-form-dialog.component.ts
- projects/portal/src/app/views/ecosystemincentive/incentive.component.html
- projects/portal/src/app/views/ecosystemincentive/incentive.component.ts
- projects/portal/src/app/views/nftbackedloan/borrowers/borrow/borrow.component.ts
- projects/portal/src/app/views/nftbackedloan/borrowers/repay/repay.component.ts
- projects/portal/src/app/views/nftbackedloan/lenders/lender/lender.component.ts
- projects/portal/src/app/views/nftbackedloan/lenders/place-bid/place-bid.component.ts
- projects/portal/src/app/views/nftbackedloan/nfts/class/nft/bidder-nft/bidder-nft.component.ts
- projects/portal/src/app/views/nftbackedloan/nfts/class/nft/lister-nft/lister-nft.component.ts
- projects/portal/src/app/views/nftbackedloan/nfts/class/nft/nft.component.ts
Use this ver ununifi-ts to fix class_id related Query
https://github.com/cosmos-client/ununifi-ts/pull/32
> ununifi-client v4.0.0-rc fix query

- projects/portal/src/app/models/band-protocols/band-protocol.service.ts
- projects/portal/src/app/models/yield-aggregators/yield-aggregator.query.service.ts
- projects/portal/src/app/pages/yieldaggregator/vaults/deposit/deposit.component.html
- projects/portal/src/app/pages/yieldaggregator/vaults/deposit/deposit.component.ts
- projects/portal/src/app/pages/yieldaggregator/vaults/owner/owner.component.ts
- projects/portal/src/app/pages/yieldaggregator/vaults/vault/vault.component.ts
- projects/portal/src/app/pages/yieldaggregator/vaults/vaults.component.html
- projects/portal/src/app/pages/yieldaggregator/vaults/vaults.component.ts
- projects/portal/src/app/pages/yieldaggregator/yield-aggregator-routing.module.ts
- projects/portal/src/app/pages/yieldaggregator/yield-aggregator.module.ts
- projects/portal/src/app/views/yieldaggregator/vaults/deposit/deposit.component.html
- projects/portal/src/app/views/yieldaggregator/vaults/deposit/deposit.component.ts
- projects/portal/src/app/views/yieldaggregator/vaults/deposit/deposit.module.ts
- projects/portal/src/app/views/yieldaggregator/vaults/owner/owner.component.html
- projects/portal/src/app/views/yieldaggregator/vaults/vaults.component.html
- projects/portal/src/app/views/yieldaggregator/vaults/vaults.component.ts
- Number of Vault tokens in Balance
- Vault Asset Symbol
- Valuation Market value
- Total deposited amount (USD)
> Deposited Vaults

- projects/portal/src/app/views/yieldaggregator/vaults/vault/vault.component.html
Temporarily removes the display of Total
Disable chain select submit (bug)
> fix: delete total of redeem (temp)

- package-lock.json
- package.json
- projects/portal/src/app/views/yieldaggregator/vaults/vault/vault.component.html
> #637 IYA redeem total_amount

- projects/explorer/editions/ununifi/launch/ununifi-test/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi-test/firebase-hosting/config.js
- projects/portal/src/app/models/config.service.ts
- projects/portal/src/app/models/yield-aggregators/yield-aggregator.service.ts
- projects/portal/src/app/pages/yieldaggregator/strategies/strategies.component.html
- projects/portal/src/app/pages/yieldaggregator/strategies/strategies.component.ts
- projects/portal/src/app/pages/yieldaggregator/strategies/strategy/strategy.component.html
- projects/portal/src/app/pages/yieldaggregator/strategies/strategy/strategy.component.ts
- projects/portal/src/app/pages/yieldaggregator/vaults/vault/vault.component.html
- projects/portal/src/app/pages/yieldaggregator/vaults/vault/vault.component.ts
- projects/portal/src/app/views/yieldaggregator/strategies/strategies.component.html
- projects/portal/src/app/views/yieldaggregator/strategies/strategies.component.ts
- projects/portal/src/app/views/yieldaggregator/strategies/strategies.module.ts
- projects/portal/src/app/views/yieldaggregator/strategies/strategy/strategy.component.html
- projects/portal/src/app/views/yieldaggregator/strategies/strategy/strategy.component.ts
- projects/portal/src/app/views/yieldaggregator/vaults/vault/vault.component.html
- projects/portal/src/app/views/yieldaggregator/vaults/vault/vault.component.ts
- projects/portal/src/app/views/yieldaggregator/vaults/vaults.component.html
- projects/portal/src/assets/config.js
- Fix pool APY & display APY
- View All strategy in strategy list page
- Add description in vault detail page (coming soon text)
> Improve IYA UI

- projects/explorer/src/app/pages/txs/tx/tx-messages/tx-messages.component.html
- projects/explorer/src/app/pages/txs/tx/tx-messages/tx-messages.component.ts
- projects/explorer/src/app/pages/txs/tx/tx.component.html
- projects/explorer/src/app/pages/txs/tx/tx.component.ts
- projects/explorer/src/app/views/txs/tx/tx-common/msg-default/msg-default.component.html
- projects/explorer/src/app/views/txs/tx/tx-common/msg-default/msg-default.component.ts
- projects/explorer/src/app/views/txs/tx/tx.component.html
- projects/explorer/src/app/views/txs/tx/tx.component.ts
- projects/explorer/src/assets/config.js
> fix: tx detail page

- projects/explorer/src/app/pages/accounts/account/txs/txs.component.html
- projects/explorer/src/app/pages/accounts/account/txs/txs.component.ts
- projects/explorer/src/app/pages/dashboard/txs/txs.component.ts
- projects/explorer/src/app/pages/txs/tx/tx-messages/tx-messages.component.html
- projects/explorer/src/app/pages/txs/txs.component.ts
- projects/explorer/src/app/views/accounts/account/staking/staking.component.html
- projects/explorer/src/app/views/accounts/account/txs/txs.component.html
- projects/explorer/src/app/views/accounts/account/txs/txs.component.ts
- projects/explorer/src/app/views/accounts/account/txs/txs.module.ts
- projects/explorer/src/app/views/dashboard/txs/txs.component.html
- projects/explorer/src/app/views/txs/tx/tx-common/msg-default/msg-default.component.html
- projects/explorer/src/app/views/txs/txs.component.html
- projects/explorer/src/app/views/txs/txs.component.ts
- projects/portal/src/app/views/home/txs/txs.component.html
close #662 
Fixed a bug in the Tx list, now all Tx can be retrieved.
- explorer (top page)
- explorer/txs
- explorer/accounts/{{address}}
> fix: txs-query

- package-lock.json
- package.json
- projects/explorer/src/app/pages/proposals/proposal/proposal.component.html
- projects/explorer/src/app/pages/proposals/proposal/proposal.component.ts
- projects/explorer/src/app/views/proposals/proposal/proposal.component.html
- projects/explorer/src/app/views/proposals/proposal/proposal.component.ts
- projects/portal/src/app/pages/vote/proposals/proposal/proposal.component.html
- projects/portal/src/app/pages/vote/proposals/proposal/proposal.component.ts
- projects/portal/src/app/views/vote/proposals/proposal/proposal.component.html
- projects/portal/src/app/views/vote/proposals/proposal/proposal.component.ts
- Improve `Quorum`, `Threshold` & `Veto Threshold`
- Fix Deposit card
> Proposal redesign

- projects/portal/src/app/pages/yieldaggregator/vaults/create/create.component.html
- projects/portal/src/app/pages/yieldaggregator/vaults/create/create.component.ts
- projects/portal/src/app/views/yieldaggregator/vaults/create/create.component.html
- projects/portal/src/app/views/yieldaggregator/vaults/create/create.component.ts
Fixed a bug on the vault creation page.
> fix: available tokens

- projects/portal/editions/ununifi/launch/ununifi/firebase-hosting/config.js
> feat: add pool config

- projects/explorer/src/app/pages/accounts/yieldaggregator/address/address.component.ts
- projects/explorer/src/app/pages/accounts/yieldaggregator/yieldaggregator.component.ts
- projects/explorer/src/app/views/accounts/yieldaggregator/yieldaggregator.component.html
Add loading dialog during download CSV
> fix: CSV download loading

- projects/explorer/src/app/views/proposals/proposal/proposal.component.html
- projects/portal/src/app/views/vote/proposals/proposal/proposal.component.html
close #520
It is difficult to parse all Proposal Msg, so display the JSON as it is.
> feat: proposal messages

- projects/explorer/src/app/views/proposals/proposal/proposal.component.html
- projects/portal/editions/ununifi/launch/ununifi/firebase-hosting/config.js
- projects/portal/src/app/app.module.ts
- projects/portal/src/app/models/yield-aggregators/yield-aggregator.application.service.ts
- projects/portal/src/app/models/yield-aggregators/yield-aggregator.model.ts
- projects/portal/src/app/pages/yieldaggregator/vaults/vault/vault.component.ts
- projects/portal/src/app/pipes/coin-amount.pipe.ts
- projects/portal/src/app/views/dialogs/txs/tx-confirm/tx-confirm-dialog.component.ts
- projects/portal/src/app/views/dialogs/txs/withdraw-fee-confirm/withdraw-fee-confirm-dialog.component.html
- projects/portal/src/app/views/dialogs/txs/withdraw-fee-confirm/withdraw-fee-confirm-dialog.component.ts
- projects/portal/src/app/views/dialogs/txs/withdraw-fee-confirm/withdraw-fee-confirm-dialog.module.ts
- projects/portal/src/app/views/vote/proposals/proposal/proposal.component.html
- projects/portal/src/app/views/yieldaggregator/vaults/vault/vault.component.ts
Alerts when fees exceed 50 percent.
> High Withdraw Fee Alert Dialog

- projects/portal/editions/ununifi/launch/ununifi/firebase-hosting/config.js
- projects/portal/src/app/models/config.service.ts
- projects/portal/src/app/models/yield-aggregators/yield-aggregator.model.ts
- projects/portal/src/app/models/yield-aggregators/yield-aggregator.service.ts
- projects/portal/src/app/pages/yieldaggregator/strategies/strategy/strategy.component.ts
- projects/portal/src/app/pages/yieldaggregator/vaults/vault/vault.component.ts
- projects/portal/src/app/pages/yieldaggregator/vaults/vaults.component.ts
- projects/portal/src/app/views/yieldaggregator/strategies/strategy/strategy.component.html
- projects/portal/src/app/views/yieldaggregator/strategies/strategy/strategy.component.ts
- projects/portal/src/app/views/yieldaggregator/vaults/vault/vault.component.html
- projects/portal/src/app/views/yieldaggregator/vaults/vault/vault.component.ts
- projects/portal/src/app/views/yieldaggregator/vaults/vaults.component.ts
Withdraw Option Redesign
- The default is with unbonding
- Entering the amount will show the fee and the amount redeemed.
- If multiple strategies are included, display the unbonding time for each
e.g. deposit
chain option is now disabled
> feat: withdraw options redesign

- projects/explorer/src/app/pages/accounts/account/txs/txs.component.ts
- projects/explorer/src/app/views/accounts/account/account.component.html
- projects/explorer/src/app/views/accounts/account/distribution/distribution.component.html
- projects/explorer/src/app/views/accounts/account/staking/staking.component.html
- projects/explorer/src/app/views/accounts/account/txs/txs.component.html
- projects/portal/src/app/pages/balance/balance.component.html
- projects/portal/src/app/pages/balance/balance.component.ts
- projects/portal/src/app/views/accounts/account/account.component.html
- projects/portal/src/app/views/accounts/account/account.component.ts
- projects/portal/src/app/views/balance/balance.component.html
- projects/portal/src/app/views/balance/balance.component.ts
Add vesting detail card in Portal Top page & Explorer Account Detail page
> Vesting Amount in Portal Top & Explorer Accpunt Detail

- projects/landing-page-html/advanced/index.html
- projects/landing-page-html/beginner/index.html
> fix: delete background

- projects/landing-page-html/advanced/index.html
- projects/landing-page-html/beginner/index.html
- projects/landing-page-html/education/index.html
- projects/landing-page-html/index.html
> Enable portal

- projects/landing-page-html/advanced/index.html
- projects/landing-page-html/beginner/index.html
- projects/landing-page-html/education/index.html
- projects/landing-page-html/index.html
- projects/portal/src/app/views/apps/app-interest-rate-swap/app-interest-rate-swap.component.html
- projects/portal/src/app/views/interest-rate-swap/pools/pool/pool.component.html
- projects/portal/src/app/views/interest-rate-swap/simple-vaults/simple-vault/simple-vault.component.html
- projects/portal/src/app/views/interest-rate-swap/vaults/vault/vault.component.html
- projects/portal/src/app/views/yieldaggregator/strategies/strategies.component.html
Fix
- In Earn, Zero is not displayed when no balance exists
- Pool Token name  e.g. `LP {{ vault.name }}  #{{ num }}`
- Add side nav link `Vaults (Trade)`
- Pool APY display
- Input token label width
- Twitter link
> fix: IRS portal design & display feedbacks
