UnUniFi/web-apps

- projects/explorer/src/app/models/config.service.ts
- projects/portal/src/app/models/config.service.ts
@YasunoriMATSUOKA Review plz. And https://github.com/UnUniFi/utils/pull/245
Multiple Nodes Support.
- Nodes are chosen at random from config.js
- Use configs array https://github.com/UnUniFi/utils/pull/245
> Feature/Multiple-node-support part of #40

- projects/portal/src/app/models/cosmos/bank.application.service.ts
- projects/portal/src/app/utils/converter.ts
- projects/portal/src/app/utils/validater.ts
Please review.
Fixed a code that didn't work as intended when entering the appropriate private key (like 1234).
Currently, it is detected that it is not Uint8Array, but Uint8Array with a length of 0 is returned, 
So, it has been modified to check the length of Uint8Array.
> fix: private key validation

- projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.html
- projects/portal/src/app/views/staking/create-validator/create-validator.component.html
- Minimum Gas Price can now be entered on following components.
- delegate form
- redelegate form
- undelegate form
- create validator page
@YasunoriMATSUOKA plz review
> hotfix: minimum gas price readonly

- projects/portal/src/app/views/dialogs/delegate/delegate-menu-dialog/delegate-menu-dialog.component.html
If the Validator is not set website, the web site field is empty and routing to portal top page.
After the merge, the field will not be shown in such case.
> fix: if empty validator website, disable website link

- projects/explorer/src/app/pages/dashboard/dashboard.component.html
- projects/explorer/src/app/pages/dashboard/dashboard.component.ts
- projects/explorer/src/app/pages/dashboard/dashboard.module.ts
- projects/explorer/src/app/pages/dashboard/txs/txs.component.html
- projects/explorer/src/app/pages/dashboard/txs/txs.component.ts
- projects/explorer/src/app/pages/home/home.component.ts
- projects/explorer/src/app/pages/monitor/monitor.component.ts
- projects/explorer/src/app/views/dashboard/blocks/blocks.component.html
- projects/explorer/src/app/views/dashboard/dashboard.component.html
- projects/explorer/src/app/views/dashboard/txs/txs.component.html
- projects/explorer/src/app/views/dashboard/txs/txs.component.ts
- projects/explorer/src/app/views/dashboard/txs/txs.module.ts
- projects/explorer/src/app/views/dashboard/validators/validators.component.html
- projects/explorer/src/app/views/validators/validators.component.html
- Add the transaction view in dashboard
- Margin adjustment
- Add the Blocks view loading animation
- Some minor changes
The tx rest API is heavy and takes a long time to retrieve. 
So, I have made it possible to switch msgType. 
To list all transactions, the data should be stored somewhere else to list all transactions. 
I am currently looking to do a mainnet launch with this implementation, OK?
@YasunoriMATSUOKA plz review.
> feat: add txs in explorer's dashboard

- projects/portal/src/app/app.module.ts
- projects/portal/src/app/pages/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.html
- projects/portal/src/app/pages/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.ts
- projects/portal/src/app/pages/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.html
- projects/portal/src/app/pages/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.ts
- projects/portal/src/app/pages/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/delegate/invalid-validator-confirm-dialog/inactive-validator-confirm-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/invalid-validator-confirm-dialog/inactive-validator-confirm-dialog.component.ts
- projects/portal/src/app/views/dialogs/delegate/invalid-validator-confirm-dialog/inactive-validator-confirm-dialog.module.ts
- projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.ts
> fix: delegate dialog to disable redelegate same validator and warn on delegate to an inactive validator

- projects/explorer/src/app/pages/dashboard/dashboard.component.html
- projects/explorer/src/app/pages/dashboard/txs/txs.component.ts
- projects/explorer/src/app/views/dashboard/dashboard.component.html
- Fixed problem with loading screen not ending when there is no tx.
- Improved mobile display
> fix: Txs not showing in Dashboard when no txs

- projects/portal/src/app/views/dialogs/wallets/connect-wallet-start-dialog/connect-wallet-start-dialog.component.html
- projects/portal/src/app/views/toolbar/toolbar.component.html
close #115
- Replace `------>` to mat-icon in connect wallet dialog.
- Changed to show only icon (Connect Wallet) on mobile.
> fix: connect wallet UI

- projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/delegate-menu-dialog/delegate-menu-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.html
- projects/portal/src/app/views/dialogs/vote/deposit/deposit-form-dialog.component.html
- projects/portal/src/app/views/dialogs/vote/vote/vote-form-dialog.component.html
This issue was mentioned https://github.com/UnUniFi/beta-test/issues/37
- Solved the problem of not displaying all forms when there is only a small display area. 
Scrolling can display it.
- delagate-menu
- delegate-form
- redelegate-form
-  undelegate-form
- deposit-form
- vote-form
example
> fix: scroll enabled on some dialog

- projects/portal/src/app/app.component.ts
@Senna46, 
cc : @YasunoriMATSUOKA 
Sorry, I made wrong fix. [https://github.com/UnUniFi/web-apps/pull/100/files](https://github.com/UnUniFi/web-apps/pull/100/files)
So fix again, please review.
I ran the portal and explorer with the command `npm run start:all` on the local PC, 
then entered the block number in the search bar in portal, and confirmed that the page transitioned correctly.
> fix: redirect url on portal search bar

- projects/portal/src/app/models/auctions/auction.infrastructure.service.ts
- projects/portal/src/app/models/cdps/cdp.infrastructure.service.ts
- projects/portal/src/app/models/cosmos/bank.service.ts
- projects/portal/src/app/models/cosmos/gov.service.ts
- projects/portal/src/app/models/cosmos/staking.service.ts
- Other Account Type convert BaseAccount
Function check list
sample
```
const sdk = await this.cosmosSDKService.sdk().then((sdk) => sdk.rest);
const account = await rest.auth
.account(sdk, accAddress)
.then((res) => res.data.account && cosmosclient.codec.unpackCosmosAny(res.data.account))
.catch((_) => undefined);
const baseAccount = convertUnknownAccountToBaseAccount(account);
if (!baseAccount) {
throw Error('Unused Account or Unsupported Account Type!');
}
```
> fix: allow transactions to be executed on account types other than BaseAccount

- projects/landing-page/src/app/views/home/home.component.css
- projects/landing-page/src/app/views/home/home.component.html
[https://github.com/UnUniFi/web-apps/issues/155](https://github.com/UnUniFi/web-apps/issues/155)
Please review.
I fix LP by deketing some images when window size smaller then md ( same as "man.img" )
> fix: delete some img when window size is for mobile

- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-create-wallet-form-dialog/ununifi-create-wallet-form-dialog.component.html
@mkXultra @Senna46 
plz review 🙏 
Without this PR fix, unexpected another new account that is different from the expected import account will be restored.
In another word, before fix, if you import with create-dialog then you will get another address (create newly on 1st view) and it is saved on the backup file and IndexedDB. It is terrible.
Before fix ... restored account at create-dialog is different with restored account at import-dialog. this is terrible bug.
After fix ... restoration account at create-dialog is disabled. at create-dialog, only create is enabled. restored account at import-dialog is same and correct.
> fix: disable import feature on create dialog

- projects/portal/src/app/views/delegate/validators/validator/validator.component.html
- projects/portal/src/app/views/dialogs/delegate/delegate-menu-dialog/delegate-menu-dialog.component.html
@YasunoriMATSUOKA , @Senna46
Please review.
-  Add the "min_self_delegate" item to the validator details page, because  "min_self_delegate" is editable and it is better to be able to see the current value,
-  Fixed that only the link can be clicked.
> feat: fix-delegate-menu

- projects/portal/src/app/models/cosmos/bank.application.service.ts
- projects/portal/src/app/models/cosmos/bank.service.ts
- projects/portal/src/app/models/cosmos/tx-common.service.ts
- projects/portal/src/app/models/wallets/metamask/metamask.infrastructure.service.ts
I succeeded to send transaction with metamask in local testnet.
@jununifi @YasunoriMATSUOKA 
Caution: Only bank send is supported. Other tx types need to be modified for using address not calculated by pubkey.
> feat: metamask successfully sent

- projects/explorer/src/app/app.component.ts
- projects/marketplace/src/app/app.component.ts
- projects/portal/src/app/app.component.ts
When entering upper case numbers in the search bar at the top, an error occurs when converting BigInt.
There is a` try-catch`, but a deeper nesting error could not be detected.
So I added `try-catch`.
‐ before
‐ after
> fix: Add search bar error handling 

- projects/marketplace/editions/ununifi/launch/ununifi-8-private-test/firebase-hosting/config.js
- projects/marketplace/editions/ununifi/launch/ununifi-9-beta-test-v1/firebase-hosting/config.js
- projects/marketplace/editions/ununifi/launch/ununifi-alpha-test/firebase-hosting/config.js
- projects/marketplace/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
- projects/marketplace/editions/ununifi/launch/ununifi-test/firebase-hosting/config.js
- projects/marketplace/editions/ununifi/launch/ununifi/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi-8-private-test/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi-9-beta-test-v1/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi/firebase-hosting/config.js
@yutaro-elk, cc @KimuraYu45z 
Fixed typo in chain-name.
I searched for `Ununufi` in VCcode and replaced it mechanically.
Since the beta-testnet environment could not be reproduced at Local,
I have confirmed that the chain-name is visible in kepler.
Please, review 🙏
> fix: typo ununufi at develop branch (alpha-testnet)

- projects/portal/src/app/app.module.ts
- projects/portal/src/app/models/cosmos/distribution.application.service.ts
- projects/portal/src/app/models/cosmos/distribution.service.ts
- projects/portal/src/app/pages/balance/balance.component.html
- projects/portal/src/app/pages/balance/balance.component.ts
- projects/portal/src/app/pages/balance/balance.usecase.service.ts
- projects/portal/src/app/pages/dialogs/delegate/withdraw-all-delegator-reward-form-dialog/withdraw-all-delegator-reward-form-dialog.component.html
- projects/portal/src/app/pages/dialogs/delegate/withdraw-all-delegator-reward-form-dialog/withdraw-all-delegator-reward-form-dialog.component.ts
- projects/portal/src/app/pages/dialogs/delegate/withdraw-all-delegator-reward-form-dialog/withdraw-all-delegator-reward-form-dialog.module.ts
- projects/portal/src/app/views/balance/balance.component.html
- projects/portal/src/app/views/balance/balance.component.ts
- projects/portal/src/app/views/cosmos/staking/validators/validator/validator.component.html
- projects/portal/src/app/views/delegate/validators/validators.component.html
- projects/portal/src/app/views/dialogs/delegate/delegate-menu-dialog/delegate-menu-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/withdraw-all-delegator-reward-form-dialog/withdraw-all-delegator-reward-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/withdraw-all-delegator-reward-form-dialog/withdraw-all-delegator-reward-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/delegate/withdraw-all-delegator-reward-form-dialog/withdraw-all-delegator-reward-form-dialog.module.ts
- projects/portal/src/app/views/dialogs/delegate/withdraw-delegator-reward-form-dialog/withdraw-delegator-reward-form-dialog.component.html
- projects/portal/src/app/views/dialogs/delegate/withdraw-validator-commission-form-dialog/withdraw-validator-commission-form-dialog.component.html
close #231 
This PR update #232.
- `Delegates` above `Validators`
- Shares => Rewards (ex. Claimable Delegator Reward)
- Withdraw => Claim
ex 
=> Next comment
- Add `Claimable Delegator Reward` on Balance page
- Add `Claim All Rewards` button
> Delegator rewards on Balance page

- projects/portal/src/app/models/cosmos/gov.application.service.ts
- projects/portal/src/app/models/cosmos/staking.application.service.ts
- projects/portal/src/app/models/cosmos/tx-common.service.ts
- projects/portal/src/app/models/wallets/wallet.application.service.ts
- projects/portal/src/app/views/dialogs/wallets/connect-wallet-completed-dialog/connect-wallet-completed-dialog.component.html
- projects/portal/src/app/views/dialogs/wallets/connect-wallet-completed-dialog/connect-wallet-completed-dialog.component.ts
- projects/portal/src/app/views/dialogs/wallets/connect-wallet-start-dialog/connect-wallet-start-dialog.component.html
- projects/portal/src/app/views/dialogs/wallets/connect-wallet-start-dialog/connect-wallet-start-dialog.component.ts
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-backup-mnemonic-and-private-key-wizard-dialog/ununifi-backup-mnemonic-and-private-key-wizard-dialog.component.html
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-backup-mnemonic-and-private-key-wizard-dialog/ununifi-backup-mnemonic-and-private-key-wizard-dialog.component.ts
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-backup-private-key-wizard-dialog/ununifi-backup-private-key-wizard-dialog.component.html
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-backup-private-key-wizard-dialog/ununifi-backup-private-key-wizard-dialog.component.ts
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-create-wallet-form-dialog/ununifi-create-wallet-form-dialog.component.html
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-create-wallet-form-dialog/ununifi-create-wallet-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-mnemonic-form-dialog/ununifi-import-wallet-with-mnemonic-form-dialog.component.html
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-mnemonic-form-dialog/ununifi-import-wallet-with-mnemonic-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-private-key-form-dialog/ununifi-import-wallet-with-private-key-form-dialog.component.html
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-private-key-form-dialog/ununifi-import-wallet-with-private-key-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-key-form-dialog/ununifi-key-form-dialog.component.html
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-key-form-dialog/ununifi-key-form-dialog.component.ts
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-select-create-import-dialog/ununifi-select-create-import-dialog.component.html
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-select-create-import-dialog/ununifi-select-create-import-dialog.component.ts
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-select-wallet-dialog/ununifi-select-wallet-dialog.component.html
- projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-select-wallet-dialog/ununifi-select-wallet-dialog.component.ts
- projects/portal/src/styles.css
- portal
- ununifi key form dialog
- ununifi create wallet form dialog
- ununifi backup private key wizard dialog
- ununifi import wallet with private key form dialog
- ununifi bakup mnemonic and private key wizard dialog
- ununifi import wallet with mnemonic form dialog
- connect wallet completed dialog
- ununifi select wallet dialog
- ununifi select import dialog
- connect wallet start dialog
> refactor: [wallet app dialog]Abolish MatDialog and use Dialog of Angular CDK

- projects/explorer/editions/ununifi/launch/ununifi-alpha-test/firebase-hosting/config.js
- projects/explorer/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
- projects/explorer/editions/ununifi/launch/ununifi-stable/firebase-hosting/config.js
- projects/explorer/src/app/models/config.service.ts
- projects/explorer/src/assets/config.js
- projects/portal/editions/ununifi/launch/ununifi-alpha-test/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi-stable/firebase-hosting/config.js
- projects/portal/src/app/app-routing.module.ts
- projects/portal/src/app/app.component.ts
- projects/portal/src/app/models/config.service.ts
- projects/portal/src/app/models/wallets/wallet-developer.guard.ts
- projects/portal/src/app/pages/developers/developers-routing.module.ts
- projects/portal/src/app/pages/developers/developers.component.html
- projects/portal/src/app/pages/developers/developers.component.ts
- projects/portal/src/app/pages/developers/developers.module.ts
- projects/portal/src/app/pages/nfts/mint/mint.component.ts
- projects/portal/src/app/views/developers/developers.component.html
- projects/portal/src/app/views/developers/developers.component.ts
- projects/portal/src/app/views/developers/developers.module.ts
- projects/portal/src/assets/config.js
Only Available for Stable & Alpha
Only Dev-users can use
> Developer node operations

- projects/landing-page-html/index.html
when user clicks on “Whitepaper” or “One Pager” it will open pdf in new browser tab instead of automatically downloading.
> feat: target=_blank

- projects/portal/src/app/models/cosmos/tx-common.service.ts
- projects/shared/src/lib/models/cosmos/tx/common/tx-common.service.ts
Tx Briadcast mode change
After sdk v0.47.x, merge this branch.
Block => Sync
```
Broadcast mode block was deprecated and has been removed. Please use sync mode instead. When upgrading your tests from block to sync and checking for a transaction code, you need to query the transaction first (with its hash) to get the correct code.
```
https://github.com/cosmos/cosmos-sdk/blob/v0.47.0/UPGRADING.md#broadcast-mode
> fix: tx-mode block => sync

- projects/portal/src/app/models/cosmos/tx-common.application.service.ts
- projects/portal/src/app/models/cosmos/tx-common.service.ts
close #493
The Tx mode block has been eliminated in v47.
This PR checks the block in which Tx is located and waits until the latest height catches up with it further.
@KimuraYu45z 
Please check.
Should I add a timeout for Tx jams?
> fix: tx include block

- projects/explorer/src/app/pages/blocks/block/block.component.ts
- projects/explorer/src/app/pages/blocks/blocks.component.ts
- projects/explorer/src/app/pages/dashboard/blocks/blocks.component.ts
close #58 
close #122
Responses of block_hash & proposer_address are base64 encorded.
Decode as following
```
bese64=>Byte Array=>Hex String
Proposer base64=>Byte Array=>bach32string with valconspub prefix
```
> fix: block & proposer base64 encode

- projects/explorer/editions/ununifi/launch/ununifi-test/firebase-hosting/config.js
- projects/portal/editions/ununifi/launch/ununifi-test/firebase-hosting/config.js
- projects/portal/src/app/models/config.service.ts
- projects/portal/src/app/models/yield-aggregators/yield-aggregator.model.ts
- projects/portal/src/app/models/yield-aggregators/yield-aggregator.service.ts
- projects/portal/src/app/pages/yieldaggregator/strategies/strategy/strategy.component.html
- projects/portal/src/app/pages/yieldaggregator/strategies/strategy/strategy.component.ts
- projects/portal/src/app/pages/yieldaggregator/vaults/vault/vault.component.ts
- projects/portal/src/app/views/yieldaggregator/strategies/strategy/strategy.component.html
- projects/portal/src/app/views/yieldaggregator/strategies/strategy/strategy.component.ts
- projects/portal/src/app/views/yieldaggregator/vaults/vault/vault.component.html
- projects/portal/src/assets/config.js
Change the APR of the Osmosis pool from hard-coded to API
Endpoint https://api-osmosis.imperator.co/apr/v2/1
Ref https://api-osmosis.imperator.co/swagger/#/apr/apr_per_pool_id
Currently, the sum of apr_superfluid is displayed as APR. Should be improved if there is a bette one.
> Osmosis Pool APR from API

- projects/portal/src/app/models/yield-aggregators/yield-aggregator.application.service.ts
- projects/portal/src/app/views/dialogs/txs/tx-confirm/tx-confirm-dialog.component.ts
- projects/portal/src/app/views/yieldaggregator/vaults/create/create.component.html
- projects/portal/src/app/views/yieldaggregator/vaults/vault/vault.component.html
- projects/portal/src/app/views/yieldaggregator/vaults/vaults.component.html
- projects/portal/src/app/views/yieldaggregator/yield-aggregator.component.html
Committed to Develop directory
> fix: iya text fix

- projects/portal/src/app/pages/yieldaggregator/vaults/vault/vault.component.ts
- projects/portal/src/app/views/yieldaggregator/vaults/vault/vault.component.html
- projects/portal/src/app/views/yieldaggregator/vaults/vault/vault.component.ts
- projects/portal/src/app/views/yieldaggregator/vaults/vaults.component.html
- With Unbonding Period toggle
- Vaults list description
aaaaaaaaa.... is test for overflow. Nothing is shown in the release version.
> Vault description in list & unbonding option(disabled)

- projects/explorer/src/app/pages/proposals/proposal/proposal.component.ts
- projects/portal/src/app/pages/vote/proposals/proposal/proposal.component.ts
- projects/portal/src/app/views/vote/proposals/proposal/proposal.component.ts
Quorum = TotalVotingPower / TotalBindedTokens
Fixed a bug in the display that was dividing by the TotalSupply.
Cosmos SDK
```
// If there is not enough quorum of votes, the proposal fails
percentVoting := totalVotingPower.Quo(sdk.NewDecFromInt(keeper.sk.TotalBondedTokens(ctx)))
quorum, _ := sdk.NewDecFromStr(params.Quorum)
if percentVoting.LT(quorum) {
return false, params.BurnVoteQuorum, tallyResults
}
```
> fix: quorum

- projects/portal/src/app/models/band-protocols/band-protocol.service.ts
- projects/portal/src/app/pages/yieldaggregator/vaults/deposit/deposit.component.html
- projects/portal/src/app/pages/yieldaggregator/vaults/deposit/deposit.component.ts
- projects/portal/src/app/pages/yieldaggregator/vaults/vault/vault.component.html
- projects/portal/src/app/pages/yieldaggregator/vaults/vault/vault.component.ts
- projects/portal/src/app/pages/yieldaggregator/vaults/vaults.component.html
- projects/portal/src/app/pages/yieldaggregator/vaults/vaults.component.ts
- projects/portal/src/app/views/yieldaggregator/vaults/deposit/deposit.component.html
- projects/portal/src/app/views/yieldaggregator/vaults/deposit/deposit.component.ts
- projects/portal/src/app/views/yieldaggregator/vaults/vault/vault.component.html
- projects/portal/src/app/views/yieldaggregator/vaults/vault/vault.component.ts
- projects/portal/src/app/views/yieldaggregator/vaults/vaults.component.html
- projects/portal/src/app/views/yieldaggregator/vaults/vaults.component.ts
Speeds up loading by reducing the number of APIs to kick when loading the Vault List.
- before
Each of the Osmosis and Oracle APIs were executed in a number of vaults.
- after
The Osmosis API is executed only once. 
Oracle API is executed as many times as the number of tokens present in the vault.
> UYA Faster loading

- projects/portal/editions/ununifi/launch/gluon-beta/firebase-hosting/config.js
- projects/portal/src/app/views/interest-rate-swap/pools/pool/pool.component.html
- projects/portal/src/app/views/interest-rate-swap/vaults/vault/vault.component.html
`PT {{vault_underlying_token}} #{{tranche_id}}`
The balance page is unable to get the vault information due to technical difficulties and simply shows `PT #{{tranche_id}}`
It is quite difficult to get `vault_underlying_token`, because we can only get the denom irs/tranche/1/pt from the balance query, so we need to do some looping to get the vault information from here.
I'll add a query to the backend and address it in a future update.
> PT (YT & LP) name change
